/**
 * iOS RoomPlan client — wraps the @restoreassist/capacitor-room-plan native plugin.
 *
 * The native plugin (capacitor-plugins/room-plan/) uses ARKit RoomPlan API
 * (iOS 16+, iPhone 12 Pro+ / iPad Pro with LiDAR sensor) to perform room
 * scans and returns structured floor-plan data.
 *
 * On non-iOS platforms (Android, web) isAvailable() returns false and
 * callers should fall back to manual entry or the BLE tape client.
 *
 * Plugin contract:
 *   startScan()  → resolves when user taps "Done" in the AR view
 *   getScanData() → returns latest scan result
 *
 * RA-1133 Tier 1
 */

import { Capacitor } from "@capacitor/core";

// ─── TYPES ────────────────────────────────────────────────────────────────────

export interface RoomPlanWall {
  id: string;
  length: number; // metres
  height: number; // metres
  confidence: "high" | "medium" | "low";
}

export interface RoomPlanOpening {
  wallId: string;
  type: "door" | "window" | "opening";
  width: number; // metres
  height: number; // metres
  distanceFromFloor: number; // metres
}

export interface RoomPlanResult {
  /** Unique session ID generated by the plugin */
  scanId: string;
  roomName: string | null;
  /** Floor polygon vertices in metres (x,y in floor plane) */
  floorPolygon: Array<{ x: number; y: number }>;
  /** Computed area from polygon (m²) */
  areaSqm: number;
  /** Average ceiling height (m) */
  ceilingHeight: number;
  walls: RoomPlanWall[];
  openings: RoomPlanOpening[];
  /** Duration of scan in seconds */
  scanDuration: number;
  /** Raw USD/obj/e57 data URL (base64 or file URI) for upload */
  rawDataUri: string | null;
  /** SVG representation of the floor polygon */
  svgData: string | null;
}

// ─── PLUGIN INTERFACE ─────────────────────────────────────────────────────────

interface RoomPlanPlugin {
  checkAvailability(): Promise<{ available: boolean; reason?: string }>;
  startScan(options: { roomName?: string }): Promise<void>;
  getScanResult(): Promise<RoomPlanResult>;
  cancelScan(): Promise<void>;
}

// ─── CLIENT ───────────────────────────────────────────────────────────────────

function getPlugin(): RoomPlanPlugin | null {
  if (typeof window === "undefined") return null;
  // Capacitor registers plugins globally on the Capacitor object
  const cap = (window as unknown as Record<string, unknown>)["Capacitor"] as
    | { Plugins?: Record<string, unknown> }
    | undefined;
  return (cap?.Plugins?.["RestoreAssistRoomPlan"] as RoomPlanPlugin) ?? null;
}

export interface RoomPlanClient {
  isAvailable(): Promise<boolean>;
  startScan(roomName?: string): Promise<RoomPlanResult>;
  cancelScan(): Promise<void>;
}

class CapacitorRoomPlanClient implements RoomPlanClient {
  async isAvailable(): Promise<boolean> {
    if (!Capacitor.isNativePlatform()) return false;
    if (Capacitor.getPlatform() !== "ios") return false;
    const plugin = getPlugin();
    if (!plugin) return false;
    try {
      const { available } = await plugin.checkAvailability();
      return available;
    } catch {
      return false;
    }
  }

  async startScan(roomName?: string): Promise<RoomPlanResult> {
    const plugin = getPlugin();
    if (!plugin) throw new Error("RoomPlan plugin not available");
    await plugin.startScan({ roomName });
    return plugin.getScanResult();
  }

  async cancelScan(): Promise<void> {
    const plugin = getPlugin();
    if (!plugin) return;
    await plugin.cancelScan().catch(() => {});
  }
}

export function getRoomPlanClient(): RoomPlanClient {
  return new CapacitorRoomPlanClient();
}

/**
 * Compute area of a polygon using the shoelace formula.
 * Vertices are in metres (x,y in floor plane).
 */
export function polygonArea(vertices: Array<{ x: number; y: number }>): number {
  let area = 0;
  const n = vertices.length;
  for (let i = 0; i < n; i++) {
    const j = (i + 1) % n;
    area += vertices[i].x * vertices[j].y;
    area -= vertices[j].x * vertices[i].y;
  }
  return Math.abs(area / 2);
}

/**
 * Convert RoomPlanResult polygon to SVG path (suitable for floor plan rendering).
 * Scale: 1 metre = `pxPerMetre` pixels.
 */
export function polygonToSvg(
  vertices: Array<{ x: number; y: number }>,
  pxPerMetre = 100,
): string {
  if (vertices.length === 0) return "";
  const points = vertices
    .map((v) => `${(v.x * pxPerMetre).toFixed(1)},${(v.y * pxPerMetre).toFixed(1)}`)
    .join(" ");
  const maxX = Math.max(...vertices.map((v) => v.x)) * pxPerMetre + 20;
  const maxY = Math.max(...vertices.map((v) => v.y)) * pxPerMetre + 20;
  return `<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 ${maxX} ${maxY}" width="${maxX}" height="${maxY}"><polygon points="${points}" fill="#E0F2FE" stroke="#0369A1" stroke-width="2"/></svg>`;
}
