-- RA-1596 — Invoice.publicToken expiry + rotation support.
-- Nullable so any existing tokens stay valid until they naturally
-- get regenerated by the next `send` or explicit rotation. New
-- tokens minted after this migration land with a 90-day horizon.
ALTER TABLE "Invoice" ADD COLUMN "publicTokenExpiresAt" TIMESTAMP(3);
ALTER TABLE "Invoice" ADD COLUMN "publicTokenRotatedAt" TIMESTAMP(3);
