-- CreateSchema
CREATE SCHEMA IF NOT EXISTS "public";

-- CreateEnum
CREATE TYPE "Role" AS ENUM ('USER', 'ADMIN', 'MANAGER');

-- CreateEnum
CREATE TYPE "ClientStatus" AS ENUM ('ACTIVE', 'INACTIVE', 'PROSPECT', 'ARCHIVED');

-- CreateEnum
CREATE TYPE "ReportStatus" AS ENUM ('DRAFT', 'PENDING', 'APPROVED', 'COMPLETED', 'ARCHIVED');

-- CreateEnum
CREATE TYPE "InvitationStatus" AS ENUM ('PENDING', 'ACCEPTED', 'EXPIRED', 'REVOKED');

-- CreateEnum
CREATE TYPE "ApprovalType" AS ENUM ('SCOPE_OF_WORK', 'COST_ESTIMATE');

-- CreateEnum
CREATE TYPE "ApprovalStatus" AS ENUM ('PENDING', 'APPROVED', 'REJECTED', 'CHANGES_REQUESTED');

-- CreateEnum
CREATE TYPE "CertificationType" AS ENUM ('IICRC_WRT', 'IICRC_AMRT', 'IICRC_FSRT', 'IICRC_CCT', 'TRADE_PLUMBING', 'TRADE_ELECTRICAL', 'TRADE_BUILDING', 'TRADE_CARPENTRY', 'INSURANCE_PUBLIC_LIABILITY', 'INSURANCE_PROFESSIONAL_INDEMNITY', 'INSURANCE_WORKERS_COMP', 'BUSINESS_ABN_REGISTRATION', 'BUSINESS_GST_REGISTRATION', 'OTHER');

-- CreateEnum
CREATE TYPE "VerificationStatus" AS ENUM ('PENDING', 'VERIFIED', 'REJECTED', 'EXPIRED', 'RENEWAL_NEEDED');

-- CreateEnum
CREATE TYPE "ReviewStatus" AS ENUM ('PUBLISHED', 'DISPUTED', 'HIDDEN', 'REMOVED');

-- CreateEnum
CREATE TYPE "ReviewDisputeStatus" AS ENUM ('NONE', 'PENDING_REVIEW', 'UNDER_INVESTIGATION', 'RESOLVED_KEPT', 'RESOLVED_AMENDED', 'RESOLVED_REMOVED');

-- CreateEnum
CREATE TYPE "IntegrationStatus" AS ENUM ('CONNECTED', 'DISCONNECTED', 'ERROR', 'SYNCING');

-- CreateEnum
CREATE TYPE "IntegrationProvider" AS ENUM ('XERO', 'QUICKBOOKS', 'MYOB', 'SERVICEM8', 'ASCORA');

-- CreateEnum
CREATE TYPE "SubscriptionStatus" AS ENUM ('TRIAL', 'ACTIVE', 'CANCELED', 'EXPIRED', 'PAST_DUE');

-- CreateEnum
CREATE TYPE "EstimateStatus" AS ENUM ('DRAFT', 'INTERNAL_REVIEW', 'CLIENT_REVIEW', 'APPROVED', 'LOCKED');

-- CreateEnum
CREATE TYPE "AddonPurchaseStatus" AS ENUM ('PENDING', 'COMPLETED', 'FAILED', 'REFUNDED');

-- CreateEnum
CREATE TYPE "ClaimAnalysisBatchStatus" AS ENUM ('PENDING', 'PROCESSING', 'COMPLETED', 'FAILED', 'PARTIAL');

-- CreateEnum
CREATE TYPE "ClaimAnalysisStatus" AS ENUM ('PENDING', 'PROCESSING', 'COMPLETED', 'FAILED');

-- CreateEnum
CREATE TYPE "MissingElementCategory" AS ENUM ('IICRC_COMPLIANCE', 'OH_S_POLICY', 'WORKING_AT_HEIGHTS', 'CONFINED_SPACES', 'PPE_REQUIREMENTS', 'BILLING_ITEM', 'DOCUMENTATION', 'SCOPE_OF_WORKS', 'JOB_COSTING', 'ENVIRONMENTAL_CONTROLS', 'WASTE_DISPOSAL', 'QUALITY_CONTROL', 'OTHER');

-- CreateEnum
CREATE TYPE "MissingElementSeverity" AS ENUM ('CRITICAL', 'HIGH', 'MEDIUM', 'LOW');

-- CreateEnum
CREATE TYPE "StandardTemplateType" AS ENUM ('INITIAL_INSPECTION_REPORT', 'SCOPE_OF_WORKS', 'JOB_COSTING', 'COMPLIANCE_CHECKLIST', 'BILLING_TEMPLATE');

-- CreateEnum
CREATE TYPE "InspectionStatus" AS ENUM ('DRAFT', 'SUBMITTED', 'PROCESSING', 'CLASSIFIED', 'SCOPED', 'ESTIMATED', 'COMPLETED', 'REJECTED');

-- CreateEnum
CREATE TYPE "RegulatoryDocumentType" AS ENUM ('INSURANCE_POLICY', 'INSURANCE_REGULATION', 'BUILDING_CODE_NATIONAL', 'BUILDING_CODE_STATE', 'ELECTRICAL_STANDARD', 'PLUMBING_STANDARD', 'CONSUMER_LAW', 'INDUSTRY_BEST_PRACTICE', 'SAFETY_REGULATION');

-- CreateEnum
CREATE TYPE "UsageEventType" AS ENUM ('PROPERTY_LOOKUP', 'VOICE_TRANSCRIPTION', 'VOICE_AI_INTERACTION', 'LIDAR_SCAN', 'FLOOR_PLAN_GENERATION', 'AI_ASSISTANT_QUERY');

-- CreateEnum
CREATE TYPE "AuthorityFormStatus" AS ENUM ('DRAFT', 'PENDING_SIGNATURES', 'PARTIALLY_SIGNED', 'COMPLETED', 'CANCELLED');

-- CreateEnum
CREATE TYPE "AuthoritySignatoryRole" AS ENUM ('CLIENT', 'INSURER', 'CONTRACTOR', 'ADMIN', 'TECHNICIAN', 'MANAGER', 'PROPERTY_OWNER');

-- CreateEnum
CREATE TYPE "FormType" AS ENUM ('WORK_ORDER', 'AUTHORITY_TO_COMMENCE', 'JSA', 'SDS', 'SWIMS', 'SITE_INDUCTION', 'CUSTOM');

-- CreateEnum
CREATE TYPE "FormCategory" AS ENUM ('SAFETY', 'COMPLIANCE', 'CLIENT_INTAKE', 'JOB_DOCUMENTATION', 'INSURANCE', 'QUALITY_CONTROL', 'CUSTOM');

-- CreateEnum
CREATE TYPE "FormTemplateStatus" AS ENUM ('DRAFT', 'PUBLISHED', 'ARCHIVED', 'DEPRECATED');

-- CreateEnum
CREATE TYPE "FormSubmissionStatus" AS ENUM ('DRAFT', 'IN_PROGRESS', 'AWAITING_SIGNATURE', 'COMPLETED', 'CANCELLED', 'EXPIRED');

-- CreateEnum
CREATE TYPE "SignatureType" AS ENUM ('DIGITAL_CANVAS', 'ELECTRONIC_TYPED', 'ESIGNATURE_WORKFLOW', 'BIOMETRIC');

-- CreateEnum
CREATE TYPE "SignatoryRole" AS ENUM ('TECHNICIAN', 'SUPERVISOR', 'CLIENT', 'PROPERTY_OWNER', 'WITNESS', 'CONTRACTOR', 'OTHER');

-- CreateEnum
CREATE TYPE "FormAuditAction" AS ENUM ('CREATED', 'FIELD_UPDATED', 'SAVED', 'SUBMITTED', 'SIGNATURE_ADDED', 'ATTACHMENT_ADDED', 'ATTACHMENT_REMOVED', 'STATUS_CHANGED', 'CANCELLED', 'REOPENED');

-- CreateEnum
CREATE TYPE "InterviewStatus" AS ENUM ('STARTED', 'IN_PROGRESS', 'COMPLETED', 'ABANDONED');

-- CreateEnum
CREATE TYPE "QuestionType" AS ENUM ('YES_NO', 'MULTIPLE_CHOICE', 'TEXT', 'NUMERIC', 'MEASUREMENT', 'LOCATION', 'MULTISELECT', 'CHECKBOX');

-- CreateEnum
CREATE TYPE "SubscriptionTierLevel" AS ENUM ('STANDARD', 'PREMIUM', 'ENTERPRISE');

-- CreateEnum
CREATE TYPE "WebhookEventStatus" AS ENUM ('PENDING', 'PROCESSING', 'COMPLETED', 'FAILED', 'SKIPPED');

-- CreateEnum
CREATE TYPE "NotificationType" AS ENUM ('INFO', 'SUCCESS', 'WARNING', 'ERROR');

-- CreateEnum
CREATE TYPE "WorkflowStatus" AS ENUM ('PENDING', 'RUNNING', 'PAUSED', 'COMPLETED', 'FAILED', 'PARTIALLY_FAILED', 'CANCELLED');

-- CreateEnum
CREATE TYPE "TaskStatus" AS ENUM ('PENDING', 'READY', 'RUNNING', 'COMPLETED', 'FAILED', 'SKIPPED', 'CANCELLED', 'DEAD_LETTER');

-- CreateEnum
CREATE TYPE "InvoiceStatus" AS ENUM ('DRAFT', 'SENT', 'VIEWED', 'PARTIALLY_PAID', 'PAID', 'OVERDUE', 'CANCELLED', 'WRITTEN_OFF', 'REFUNDED');

-- CreateEnum
CREATE TYPE "PaymentMethod" AS ENUM ('STRIPE', 'BANK_TRANSFER', 'CASH', 'CHEQUE', 'CREDIT_CARD', 'PAYPAL', 'EXTERNAL', 'OTHER');

-- CreateEnum
CREATE TYPE "CreditNoteStatus" AS ENUM ('DRAFT', 'ISSUED', 'APPLIED', 'REFUNDED', 'CANCELLED');

-- CreateEnum
CREATE TYPE "CreditNoteReason" AS ENUM ('CUSTOMER_REFUND', 'PRICING_ERROR', 'DUPLICATE_INVOICE', 'SERVICE_ISSUE', 'GOODWILL', 'OTHER');

-- CreateEnum
CREATE TYPE "RecurringFrequency" AS ENUM ('WEEKLY', 'FORTNIGHTLY', 'MONTHLY', 'QUARTERLY', 'SEMI_ANNUALLY', 'ANNUALLY');

-- CreateEnum
CREATE TYPE "RecurringInvoiceStatus" AS ENUM ('ACTIVE', 'PAUSED', 'COMPLETED', 'CANCELLED');

-- CreateEnum
CREATE TYPE "InvoiceEmailType" AS ENUM ('SENT', 'REMINDER', 'THANK_YOU', 'OVERDUE');

-- CreateEnum
CREATE TYPE "ReminderType" AS ENUM ('BEFORE_DUE', 'ON_DUE_DATE', 'OVERDUE_1', 'OVERDUE_2', 'OVERDUE_3');

-- CreateEnum
CREATE TYPE "ReminderStatus" AS ENUM ('PENDING', 'SENT', 'FAILED', 'CANCELLED');

-- CreateEnum
CREATE TYPE "ExternalSyncStatus" AS ENUM ('PENDING', 'SYNCED', 'FAILED');

-- CreateEnum (RA-408: pluggable storage provider)
CREATE TYPE "StorageProviderType" AS ENUM ('SUPABASE', 'S3', 'GCS', 'AZURE');

-- CreateEnum (Sprint G: evidence intelligence — IICRC S500:2025)
CREATE TYPE "EvidenceClass" AS ENUM (
  'MOISTURE_READING',
  'THERMAL_IMAGE',
  'AMBIENT_ENVIRONMENTAL',
  'PHOTO_DAMAGE',
  'PHOTO_EQUIPMENT',
  'PHOTO_PROGRESS',
  'PHOTO_COMPLETION',
  'VIDEO_WALKTHROUGH',
  'FLOOR_PLAN',
  'SCOPE_DOCUMENT',
  'LAB_RESULT',
  'AUTHORITY_FORM',
  'EQUIPMENT_LOG',
  'TECHNICIAN_NOTE',
  'VOICE_MEMO',
  'THIRD_PARTY_REPORT',
  'COMPLIANCE_CERTIFICATE'
);

-- CreateEnum (Sprint G: workflow step state machine)
CREATE TYPE "WorkflowStepStatus" AS ENUM (
  'NOT_STARTED',
  'IN_PROGRESS',
  'COMPLETED',
  'SKIPPED',
  'BLOCKED'
);

-- CreateEnum (RA-414: AI provider connections)
CREATE TYPE "AiProvider" AS ENUM ('ANTHROPIC', 'OPENAI', 'GOOGLE', 'GEMMA');
CREATE TYPE "ProviderConnectionStatus" AS ENUM ('ACTIVE', 'FAILED', 'DISABLED');

