/**
 * generate-assessment-pdf.ts — RA-1717 follow-up.
 *
 * Renders an AssessmentGeneration (report sections + scope items +
 * estimate lines + citations + meta) as a standalone A4-portrait PDF
 * suitable for sending to insurer / claimant.
 *
 * pdf-lib uses WinAnsi encoding for StandardFonts. Em-dash (—),
 * arrows (→), bullets (•), curly quotes — all unsupported. Caller
 * input gets sanitised through `ascii()` before drawing.
 */

import {
  PDFDocument,
  StandardFonts,
  rgb,
  type PDFFont,
  type PDFPage,
} from "pdf-lib";
import type {
  AssessmentReport,
  EstimateLine,
  EstimateTotals,
  ScopeItem,
  StandardCitation,
} from "./types";

// ── Page geometry (A4 portrait) ──────────────────────────────────────────────

const PAGE_W = 595;
const PAGE_H = 842;
const MARGIN = 48;
const CONTENT_W = PAGE_W - MARGIN * 2;
const HEADER_H = 56;
const FOOTER_H = 32;
const TOP_Y = PAGE_H - MARGIN - HEADER_H;
const BOTTOM_Y = MARGIN + FOOTER_H;

const BRAND_DARK = rgb(0.11, 0.18, 0.28);
const TEXT_MAIN = rgb(0.1, 0.1, 0.1);
const TEXT_MUTED = rgb(0.45, 0.45, 0.45);
const DIVIDER = rgb(0.87, 0.87, 0.87);
const ROW_BG = rgb(0.96, 0.96, 0.96);

// ── ASCII sanitiser (WinAnsi-safe) ───────────────────────────────────────────

function ascii(input: string): string {
  return input
    .replace(/[—–]/g, "-") // em/en dash
    .replace(/•/g, "*") // bullet
    .replace(/→/g, "->") // right arrow
    .replace(/[‘’]/g, "'") // curly singles
    .replace(/[“”]/g, '"') // curly doubles
    .replace(/ /g, " ") // nbsp
    .replace(/·/g, "*") // middle dot
    .replace(/[^\x00-\xFF]/g, "?"); // any other non-WinAnsi
}

// ── Drawing primitives ───────────────────────────────────────────────────────

interface Ctx {
  doc: PDFDocument;
  page: PDFPage;
  fontReg: PDFFont;
  fontBold: PDFFont;
  y: number;
}

function newPage(ctx: Ctx, meta: AssessmentPdfInput["meta"], title: string) {
  ctx.page = ctx.doc.addPage([PAGE_W, PAGE_H]);
  drawHeader(ctx, meta, title);
  drawFooter(ctx, meta);
  ctx.y = TOP_Y - 16;
}

function ensureSpace(
  ctx: Ctx,
  needed: number,
  meta: AssessmentPdfInput["meta"],
  title: string,
) {
  if (ctx.y - needed < BOTTOM_Y) newPage(ctx, meta, title);
}

function drawHeader(ctx: Ctx, meta: AssessmentPdfInput["meta"], title: string) {
  ctx.page.drawRectangle({
    x: 0,
    y: PAGE_H - HEADER_H,
    width: PAGE_W,
    height: HEADER_H,
    color: BRAND_DARK,
  });
  ctx.page.drawText("RestoreAssist", {
    x: MARGIN,
    y: PAGE_H - 30,
    size: 14,
    font: ctx.fontBold,
    color: rgb(1, 1, 1),
  });
  ctx.page.drawText(ascii(title), {
    x: MARGIN,
    y: PAGE_H - 46,
    size: 9,
    font: ctx.fontReg,
    color: rgb(0.85, 0.85, 0.85),
  });
  const dateStr = ascii(new Date(meta.generatedAt).toISOString().slice(0, 10));
  const w = ctx.fontReg.widthOfTextAtSize(dateStr, 9);
  ctx.page.drawText(dateStr, {
    x: PAGE_W - MARGIN - w,
    y: PAGE_H - 30,
    size: 9,
    font: ctx.fontReg,
    color: rgb(0.85, 0.85, 0.85),
  });
}

function drawFooter(ctx: Ctx, meta: AssessmentPdfInput["meta"]) {
  ctx.page.drawLine({
    start: { x: MARGIN, y: BOTTOM_Y },
    end: { x: PAGE_W - MARGIN, y: BOTTOM_Y },
    thickness: 0.5,
    color: DIVIDER,
  });
  const left = ascii(
    `${meta.assessmentGenerationId} | ${meta.modelUsed ?? "rule-based"} | ${meta.latencyMs}ms`,
  );
  ctx.page.drawText(left, {
    x: MARGIN,
    y: BOTTOM_Y - 14,
    size: 7,
    font: ctx.fontReg,
    color: TEXT_MUTED,
  });
  const right = "Generated by RestoreAssist - confidential";
  const w = ctx.fontReg.widthOfTextAtSize(right, 7);
  ctx.page.drawText(right, {
    x: PAGE_W - MARGIN - w,
    y: BOTTOM_Y - 14,
    size: 7,
    font: ctx.fontReg,
    color: TEXT_MUTED,
  });
}

function wrapLines(
  text: string,
  font: PDFFont,
  size: number,
  maxW: number,
): string[] {
  const out: string[] = [];
  for (const para of text.split(/\n/)) {
    const words = para.split(/\s+/).filter(Boolean);
    let line = "";
    for (const w of words) {
      const test = line ? `${line} ${w}` : w;
      if (font.widthOfTextAtSize(test, size) <= maxW) {
        line = test;
      } else {
        if (line) out.push(line);
        line = w;
      }
    }
    if (line) out.push(line);
    if (words.length === 0) out.push("");
  }
  return out;
}

function drawWrappedText(
  ctx: Ctx,
  text: string,
  meta: AssessmentPdfInput["meta"],
  title: string,
  opts: {
    size: number;
    font: PDFFont;
    color?: ReturnType<typeof rgb>;
    lineHeight?: number;
    maxW?: number;
    indent?: number;
  },
) {
  const { size, font, color = TEXT_MAIN } = opts;
  const lineHeight = opts.lineHeight ?? size + 3;
  const maxW = opts.maxW ?? CONTENT_W;
  const indent = opts.indent ?? 0;
  const lines = wrapLines(ascii(text), font, size, maxW - indent);
  for (const line of lines) {
    ensureSpace(ctx, lineHeight, meta, title);
    ctx.page.drawText(line, {
      x: MARGIN + indent,
      y: ctx.y - size,
      size,
      font,
      color,
    });
    ctx.y -= lineHeight;
  }
}

// ── Section renderers ────────────────────────────────────────────────────────

function renderReportSections(
  ctx: Ctx,
  report: AssessmentReport,
  meta: AssessmentPdfInput["meta"],
  title: string,
) {
  drawWrappedText(ctx, "Report", meta, title, {
    size: 14,
    font: ctx.fontBold,
    color: BRAND_DARK,
    lineHeight: 20,
  });
  ctx.y -= 4;
  for (const section of report.sections) {
    drawWrappedText(ctx, section.heading, meta, title, {
      size: 10,
      font: ctx.fontBold,
      lineHeight: 14,
    });
    drawWrappedText(ctx, section.body, meta, title, {
      size: 9,
      font: ctx.fontReg,
      lineHeight: 12,
    });
    if (section.citations && section.citations.length > 0) {
      const citeText = section.citations
        .map((c) => `${c.standard} ${c.section}`)
        .join("  *  ");
      drawWrappedText(ctx, citeText, meta, title, {
        size: 8,
        font: ctx.fontReg,
        color: TEXT_MUTED,
        lineHeight: 11,
        indent: 6,
      });
    }
    ctx.y -= 8;
  }
}

interface Column {
  header: string;
  width: number;
  align?: "left" | "right";
  get: (row: unknown) => string;
}

function renderTable(
  ctx: Ctx,
  rows: unknown[],
  cols: Column[],
  meta: AssessmentPdfInput["meta"],
  title: string,
) {
  const rowH = 16;
  const headerH = 18;

  function drawHeaderRow() {
    ensureSpace(ctx, headerH + rowH, meta, title);
    let x = MARGIN;
    ctx.page.drawRectangle({
      x: MARGIN,
      y: ctx.y - headerH,
      width: CONTENT_W,
      height: headerH,
      color: ROW_BG,
    });
    for (const col of cols) {
      const text = ascii(col.header);
      const w = ctx.fontBold.widthOfTextAtSize(text, 8);
      const tx = col.align === "right" ? x + col.width - w - 4 : x + 4;
      ctx.page.drawText(text, {
        x: tx,
        y: ctx.y - headerH + 6,
        size: 8,
        font: ctx.fontBold,
        color: TEXT_MAIN,
      });
      x += col.width;
    }
    ctx.y -= headerH;
  }

  drawHeaderRow();

  for (const row of rows) {
    if (ctx.y - rowH < BOTTOM_Y) {
      newPage(ctx, meta, title);
      drawHeaderRow();
    }
    let x = MARGIN;
    for (const col of cols) {
      const text = ascii(col.get(row));
      // Truncate to one line — assessment estimate cells are short.
      let display = text;
      while (
        ctx.fontReg.widthOfTextAtSize(display, 8) > col.width - 8 &&
        display.length > 1
      ) {
        display = display.slice(0, -1);
      }
      if (display !== text) {
        display = display.slice(0, -1) + "...";
      }
      const w = ctx.fontReg.widthOfTextAtSize(display, 8);
      const tx = col.align === "right" ? x + col.width - w - 4 : x + 4;
      ctx.page.drawText(display, {
        x: tx,
        y: ctx.y - rowH + 5,
        size: 8,
        font: ctx.fontReg,
        color: TEXT_MAIN,
      });
      x += col.width;
    }
    // Row divider.
    ctx.page.drawLine({
      start: { x: MARGIN, y: ctx.y - rowH },
      end: { x: MARGIN + CONTENT_W, y: ctx.y - rowH },
      thickness: 0.3,
      color: DIVIDER,
    });
    ctx.y -= rowH;
  }
}

// ── Public API ───────────────────────────────────────────────────────────────

export interface AssessmentPdfInput {
  domain: string;
  report: AssessmentReport;
  scope: { items: ScopeItem[] };
  estimate: { lines: EstimateLine[]; totals: EstimateTotals };
  citations: StandardCitation[];
  meta: {
    assessmentGenerationId: string;
    generatedAt: Date | string;
    modelUsed: string | null;
    latencyMs: number;
    propertyAddress?: string | null;
    inspectionNumber?: string | null;
  };
}

export async function generateAssessmentPdf(
  input: AssessmentPdfInput,
): Promise<Uint8Array> {
  const doc = await PDFDocument.create();
  const fontReg = await doc.embedFont(StandardFonts.Helvetica);
  const fontBold = await doc.embedFont(StandardFonts.HelveticaBold);

  const title = `${input.domain} assessment - ${input.meta.inspectionNumber ?? input.meta.assessmentGenerationId}`;

  const ctx: Ctx = {
    doc,
    page: doc.addPage([PAGE_W, PAGE_H]),
    fontReg,
    fontBold,
    y: TOP_Y - 16,
  };
  drawHeader(ctx, input.meta, title);
  drawFooter(ctx, input.meta);

  // Property line.
  if (input.meta.propertyAddress) {
    drawWrappedText(
      ctx,
      `Property: ${input.meta.propertyAddress}`,
      input.meta,
      title,
      { size: 9, font: ctx.fontReg, color: TEXT_MUTED, lineHeight: 12 },
    );
    ctx.y -= 4;
  }

  renderReportSections(ctx, input.report, input.meta, title);

  // Scope table.
  ctx.y -= 8;
  drawWrappedText(ctx, "Scope of works", input.meta, title, {
    size: 14,
    font: ctx.fontBold,
    color: BRAND_DARK,
    lineHeight: 20,
  });
  renderTable(
    ctx,
    input.scope.items,
    [
      {
        header: "Item",
        width: CONTENT_W * 0.5,
        get: (r) => (r as ScopeItem).description,
      },
      {
        header: "Qty",
        width: CONTENT_W * 0.1,
        align: "right",
        get: (r) => String((r as ScopeItem).quantity),
      },
      {
        header: "Unit",
        width: CONTENT_W * 0.15,
        get: (r) => (r as ScopeItem).unit,
      },
      {
        header: "IICRC",
        width: CONTENT_W * 0.25,
        get: (r) => (r as ScopeItem).iicrcRef ?? "",
      },
    ],
    input.meta,
    title,
  );

  // Estimate table.
  ctx.y -= 12;
  drawWrappedText(
    ctx,
    `Estimate (AUD ex GST $${input.estimate.totals.subtotalExGst.toFixed(2)} | GST $${input.estimate.totals.gstTotal.toFixed(2)} | total $${input.estimate.totals.totalIncGst.toFixed(2)})`,
    input.meta,
    title,
    {
      size: 14,
      font: ctx.fontBold,
      color: BRAND_DARK,
      lineHeight: 20,
    },
  );
  renderTable(
    ctx,
    input.estimate.lines,
    [
      {
        header: "Line",
        width: CONTENT_W * 0.45,
        get: (r) => (r as EstimateLine).description,
      },
      {
        header: "Qty",
        width: CONTENT_W * 0.1,
        align: "right",
        get: (r) => String((r as EstimateLine).quantity),
      },
      {
        header: "Rate",
        width: CONTENT_W * 0.15,
        align: "right",
        get: (r) => `$${(r as EstimateLine).rate.toFixed(2)}`,
      },
      {
        header: "Ex GST",
        width: CONTENT_W * 0.15,
        align: "right",
        get: (r) => `$${(r as EstimateLine).lineTotalExGst.toFixed(2)}`,
      },
      {
        header: "Inc GST",
        width: CONTENT_W * 0.15,
        align: "right",
        get: (r) => `$${(r as EstimateLine).lineTotalIncGst.toFixed(2)}`,
      },
    ],
    input.meta,
    title,
  );

  // Standards index.
  if (input.citations.length > 0) {
    ctx.y -= 12;
    drawWrappedText(ctx, "Standards index", input.meta, title, {
      size: 12,
      font: ctx.fontBold,
      color: BRAND_DARK,
      lineHeight: 16,
    });
    for (const c of input.citations) {
      const line = c.note
        ? `${c.standard} ${c.section} - ${c.note}`
        : `${c.standard} ${c.section}`;
      drawWrappedText(ctx, `* ${line}`, input.meta, title, {
        size: 8,
        font: ctx.fontReg,
        color: TEXT_MUTED,
        lineHeight: 11,
        indent: 4,
      });
    }
  }

  return doc.save();
}
