name: restoreassist
region: syd
services:
  - name: web
    dockerfile_path: Dockerfile
    http_port: 3000
    instance_count: 1
    instance_size_slug: basic-xxs
    envs:
      - key: NODE_ENV
        value: production
      - key: NEXTAUTH_URL
        scope: RUN_AND_BUILD_TIME
      - key: NEXTAUTH_SECRET
        type: SECRET
        scope: RUN_AND_BUILD_TIME
      - key: DATABASE_URL
        type: SECRET
        scope: RUN_AND_BUILD_TIME
      - key: DIRECT_URL
        type: SECRET
        scope: RUN_AND_BUILD_TIME
      - key: GOOGLE_CLIENT_ID
        type: SECRET
        scope: RUN_AND_BUILD_TIME
      - key: GOOGLE_CLIENT_SECRET
        type: SECRET
        scope: RUN_AND_BUILD_TIME
      - key: GOOGLE_REDIRECT_URI
        type: SECRET
        scope: RUN_AND_BUILD_TIME
      - key: STRIPE_SECRET_KEY
        type: SECRET
        scope: RUN_AND_BUILD_TIME
      - key: INTEGRATION_ENCRYPTION_KEY
        type: SECRET
        scope: RUN_AND_BUILD_TIME
      - key: CRON_SECRET
        type: SECRET
        scope: RUN_AND_BUILD_TIME
      - key: ENABLE_REGULATORY_CITATIONS
        scope: RUN_AND_BUILD_TIME
      - key: UPLOAD_PROVIDER
        value: spaces
        scope: RUN_AND_BUILD_TIME
      - key: LOGO_UPLOAD_PROVIDER
        value: spaces
        scope: RUN_AND_BUILD_TIME
      - key: DIGITALOCEAN_SPACES_REGION
        scope: RUN_AND_BUILD_TIME
      - key: DIGITALOCEAN_SPACES_BUCKET
        scope: RUN_AND_BUILD_TIME
      - key: DIGITALOCEAN_SPACES_KEY
        type: SECRET
        scope: RUN_AND_BUILD_TIME
      - key: DIGITALOCEAN_SPACES_SECRET
        type: SECRET
        scope: RUN_AND_BUILD_TIME
      - key: DIGITALOCEAN_SPACES_CDN_DOMAIN
        scope: RUN_AND_BUILD_TIME

