name: restore-assist
region: syd
services:
- name: web
  github:
    repo: CleanExpo/RestoreAssist
    branch: main
  build_command: npm install --force --legacy-peer-deps && npm run build
  run_command: npm start
  environment_slug: node-js
  instance_count: 1
  instance_size_slug: basic-xxs
  http_port: 3000
  health_check:
    http_path: /
  envs:
  - key: NODE_ENV
    value: production
  - key: NPM_CONFIG_FORCE
    value: "true"
  - key: CI
    value: "false"
  - key: USE_NPM_INSTALL
    value: "true"
  - key: NPM_CONFIG_LEGACY_PEER_DEPS
    value: "true"
  - key: SKIP_ENV_VALIDATION
    value: "true"
