/**
 * summarise.ts — turn run-panel.sh's output into the PR comment.
 *
 *   bash run-panel.sh diff.txt | npx tsx summarise.ts > comment.md
 *
 * Exit codes:
 *   0  a report was written (findings or not)
 *   3  the panel was degraded — fewer than two model families responded
 *
 * Exit 3 is not a failure of the change under review; it is the panel saying it
 * could not do its job. CI should surface it as a neutral result, never as a red
 * check on someone's PR, because a rate-limited free model is not evidence about
 * their code.
 */

import { mergePanel, renderVerdict, type SeatResult } from "./panel";

interface PanelInput {
  diffTruncated?: boolean;
  results: SeatResult[];
}

function readStdin(): Promise<string> {
  return new Promise((resolve, reject) => {
    let data = "";
    process.stdin.setEncoding("utf8");
    process.stdin.on("data", (chunk) => (data += chunk));
    process.stdin.on("end", () => resolve(data));
    process.stdin.on("error", reject);
  });
}

async function main(): Promise<void> {
  const raw = await readStdin();

  let input: PanelInput;
  try {
    input = JSON.parse(raw) as PanelInput;
  } catch {
    process.stderr.write("summarise: stdin was not valid JSON from run-panel.sh\n");
    process.exit(2);
  }

  if (!Array.isArray(input.results)) {
    process.stderr.write("summarise: expected a `results` array\n");
    process.exit(2);
  }

  const verdict = mergePanel(input.results);
  let body = renderVerdict(verdict);

  if (input.diffTruncated) {
    // Stated in the report, not just in a log nobody opens. A partial review
    // that reads as a whole one is the failure mode worth guarding against.
    body +=
      "\n\n> The diff was truncated before review. Files beyond the cut were not looked at by any seat.";
  }

  body += "\n\n---\n_Generated by [Claude Code](https://claude.ai/code)_\n";

  // process.exit does NOT flush a pending write to a pipe, and both documented
  // callers pipe this command. Set the code and wait for the write to land.
  process.exitCode = verdict.degraded ? 3 : 0;
  await new Promise<void>((resolve, reject) => {
    process.stdout.write(body, (err) => (err ? reject(err) : resolve()));
  });
}

void main();
