/**
 * RA-1515 — Favicon. Generated by Next.js App Router at build time from the
 * ImageResponse API so we don't ship a binary asset that drifts from brand.
 *
 * Two-letter "RA" monogram on the RestoreAssist brand blue. The surrounding
 * layout (app/layout.tsx <metadata.icons>) lets Next.js serve this as both
 * `/favicon.ico` and `/icon` automatically.
 */
import { ImageResponse } from "next/og";

export const size = { width: 32, height: 32 };
export const contentType = "image/png";

export default function Icon() {
  return new ImageResponse(
    (
      <div
        style={{
          width: "100%",
          height: "100%",
          display: "flex",
          alignItems: "center",
          justifyContent: "center",
          background: "#0f172a",
          color: "#ffffff",
          fontSize: 20,
          fontWeight: 700,
          letterSpacing: "-0.05em",
          fontFamily: "system-ui, -apple-system, sans-serif",
          borderRadius: 6,
        }}
      >
        RA
      </div>
    ),
    { ...size },
  );
}
