/**
 * Visual Regression Baselines — Sub-project #7 (T11)
 *
 * 5 surfaces × 3 viewports = 15 baseline screenshots.
 *
 * Baselines are generated by running:
 *   PLAYWRIGHT_TEST_BASE_URL=https://restoreassist-sandbox.vercel.app \
 *     npx playwright test e2e/tech-visual-baselines.spec.ts --update-snapshots
 *
 * Subsequent CI runs without --update-snapshots will compare against those
 * PNG files and fail on visual regressions.
 *
 * Helpers (loginAs / seedInspection / seedAuthorisation) call the test-only
 * API routes gated by ALLOW_TEST_HELPERS, so these tests must run against
 * an environment that has that flag set.
 */

import { test, expect } from "@playwright/test";
import {
  loginAs,
  seedInspection,
  seedAuthorisation,
} from "./_helpers/auth";

// ── Viewport definitions ──────────────────────────────────────────────────────

const VIEWPORTS = [
  { name: "iphone", width: 393, height: 852 },
  { name: "ipad", width: 768, height: 1024 },
  { name: "desktop", width: 1280, height: 800 },
] as const;

// ── Surfaces × Viewports ──────────────────────────────────────────────────────

for (const vp of VIEWPORTS) {
  test.describe(`visual baselines @ ${vp.name}`, () => {
    test.use({ viewport: { width: vp.width, height: vp.height } });

    // ── Surface 1: dashboard WITH TechLicenceBanner (USER, no Authorisation) ──

    test(`dashboard with banner @ ${vp.name}`, async ({ page }) => {
      await loginAs(page, "USER");
      await page.goto("/dashboard");

      // Banner renders when the first-run checklist returns tech_iicrc steps
      // and the user has no recent Authorisation.
      await expect(
        page.getByText(/add your credentials to unlock attestations/i),
      ).toBeVisible({ timeout: 10_000 });

      await expect(page).toHaveScreenshot(`dashboard-with-banner-${vp.name}.png`);
    });

    // ── Surface 2: dashboard WITHOUT banner (Authorisation seeded < 90 days) ──

    test(`dashboard without banner @ ${vp.name}`, async ({ page }) => {
      await loginAs(page, "USER");
      await seedAuthorisation(page, {
        subjectLicenceNumber: "IICRC-1",
        whsCardNumber: "WHS-1",
      });
      await page.goto("/dashboard");

      await expect(
        page.getByText(/add your credentials to unlock attestations/i),
      ).toHaveCount(0);

      await expect(page).toHaveScreenshot(`dashboard-without-banner-${vp.name}.png`);
    });

    // ── Surface 3: inspection detail with CapturePhotoFab (status DRAFT) ──────

    test(`inspection detail with FAB @ ${vp.name}`, async ({ page }) => {
      await loginAs(page, "USER");
      await seedInspection(page, { status: "DRAFT" });
      await page.goto("/dashboard/inspections/test-inspection");

      await expect(
        page.getByRole("button", { name: /capture photo/i }),
      ).toBeVisible({ timeout: 10_000 });

      await expect(page).toHaveScreenshot(`inspection-with-fab-${vp.name}.png`);
    });

    // ── Surface 4: CapturePhotoTagModal open with preview ────────────────────

    test(`capture tag modal @ ${vp.name}`, async ({ page }) => {
      await loginAs(page, "USER");
      await seedInspection(page, { status: "DRAFT" });
      await page.goto("/dashboard/inspections/test-inspection");

      // Wait for the FAB to render before injecting the file
      await expect(
        page.getByRole("button", { name: /capture photo/i }),
      ).toBeVisible({ timeout: 10_000 });

      // The hidden file input in CapturePhotoFab; trigger it directly so we
      // don't depend on a native file picker being openable in headless mode.
      const fileInput = page.locator('input[type="file"][accept*="image"]');
      await fileInput.setInputFiles({
        name: "test.jpg",
        mimeType: "image/jpeg",
        // Minimal valid JPEG: SOI + APP0 marker + EOI
        buffer: Buffer.from([
          0xff, 0xd8, // SOI
          0xff, 0xe0, 0x00, 0x10, // APP0 marker + length
          0x4a, 0x46, 0x49, 0x46, 0x00, 0x01, // "JFIF\0" version
          0x01, 0x00, 0x00, 0x01, 0x00, 0x01, // density unit + pixel density
          0x00, 0x00, // thumbnail size (0×0)
          0xff, 0xd9, // EOI
        ]),
      });

      // Modal title is "Capture evidence" (DialogTitle in CapturePhotoTagModal)
      await expect(
        page.getByRole("heading", { name: /capture evidence/i }),
      ).toBeVisible({ timeout: 8_000 });

      await expect(page).toHaveScreenshot(`capture-tag-modal-${vp.name}.png`);
    });

    // ── Surface 5a: InspectionSignOff state A (initial, Sign Inspection CTA) ──

    test(`sign-off state A (initial) @ ${vp.name}`, async ({ page }) => {
      await loginAs(page, "USER");
      await seedInspection(page, { status: "SUBMITTED" });
      await page.goto("/dashboard/inspections/test-inspection");

      // State A: the "Sign Inspection" button is visible; no form fields yet.
      await expect(
        page.getByRole("button", { name: /sign inspection/i }),
      ).toBeVisible({ timeout: 10_000 });

      await expect(page).toHaveScreenshot(`signoff-state-a-${vp.name}.png`);
    });

    // ── Surface 5b: InspectionSignOff state C (form-unlocked, Full name field) ─

    test(`sign-off state C (form unlocked) @ ${vp.name}`, async ({ page }) => {
      await loginAs(page, "USER");
      await seedInspection(page, { status: "SUBMITTED" });
      // Seeding a recent Authorisation causes T3 mount-time probe to skip the
      // licence modal and jump straight to "form-unlocked" state.
      await seedAuthorisation(page, {
        subjectLicenceNumber: "IICRC-1",
        whsCardNumber: "WHS-1",
      });
      await page.goto("/dashboard/inspections/test-inspection");

      // State C: the "Full name" textbox is visible; modal was bypassed.
      await expect(
        page.getByRole("textbox", { name: /full name/i }),
      ).toBeVisible({ timeout: 10_000 });

      await expect(page).toHaveScreenshot(`signoff-state-c-${vp.name}.png`);
    });
  });
}
