import { NextAuthOptions } from "next-auth";
import { PrismaAdapter } from "@auth/prisma-adapter";
import GoogleProvider from "next-auth/providers/google";
import CredentialsProvider from "next-auth/providers/credentials";
import { prisma } from "./prisma";
import bcrypt from "bcryptjs";
import crypto from "crypto";
import jwt from "jsonwebtoken";
import { verifyToken as verifyTotp } from "./auth/two-factor";
import { logSecurityEvent } from "./security-audit";

/** Verify an HMAC token generated by /api/auth/google-signin. Max age: 5 minutes. */
function verifyGoogleAuthToken(email: string, token: string): boolean {
  try {
    const secret = process.env.NEXTAUTH_SECRET;
    if (!secret) return false;
    const parts = token.split(":");
    if (parts.length !== 3 || parts[0] !== "gauth") return false;
    const [, timestamp, hmac] = parts;
    const age = Date.now() - parseInt(timestamp, 10);
    if (age > 5 * 60 * 1000 || age < 0) return false; // expired or future-dated
    const expected = crypto
      .createHmac("sha256", secret)
      .update(`gauth:${email}:${timestamp}`)
      .digest("hex");
    return crypto.timingSafeEqual(
      Buffer.from(hmac, "hex"),
      Buffer.from(expected, "hex"),
    );
  } catch {
    return false;
  }
}

export const authOptions: NextAuthOptions = {
  adapter: PrismaAdapter(prisma) as any,
  providers: [
    GoogleProvider({
      clientId: process.env.GOOGLE_CLIENT_ID!,
      clientSecret: process.env.GOOGLE_CLIENT_SECRET!,
    }),
    CredentialsProvider({
      name: "credentials",
      credentials: {
        email: { label: "Email", type: "email" },
        password: { label: "Password", type: "password" },
        // RA-1587 — second-factor code. Required only when the account
        // has `twoFactorEnabled=true`. The login page collects it after
        // a `2FA_REQUIRED` error bounces the first submission.
        totp: { label: "6-digit authenticator code", type: "text" },
      },
      async authorize(credentials) {
        if (!credentials?.email || !credentials?.password) {
          return null;
        }

        const user = await prisma.user.findUnique({
          where: { email: credentials.email },
        });

        if (!user) {
          return null;
        }

        // Google sign-in path: password field carries a short-lived HMAC proof token.
        // 2FA still enforced on top — the short-lived HMAC proves the Google callback,
        // not a standing authentication.
        const isGoogleAuth = credentials.password.startsWith("gauth:");
        if (isGoogleAuth) {
          if (!verifyGoogleAuthToken(credentials.email, credentials.password)) {
            return null;
          }
        } else {
          if (!user.password) {
            return null;
          }
          const isPasswordValid = await bcrypt.compare(
            credentials.password,
            user.password,
          );
          if (!isPasswordValid) {
            return null;
          }
        }

        // RA-1587 — enforce TOTP when the account has 2FA enabled.
        // The prior `authorize()` returned a session as soon as the
        // password matched, making the "2FA enabled" flag purely
        // cosmetic. We now require a valid TOTP on every login when
        // `twoFactorEnabled` is true — including the Google-signin
        // path, so a compromised Google account still can't log in
        // without the authenticator.
        //
        // NextAuth CredentialsProvider surfaces thrown errors as
        // `?error=<message>` on the callback URL. The login page
        // treats `2FA_REQUIRED` as "show the TOTP field" and
        // `2FA_INVALID` as "wrong code".
        if (user.twoFactorEnabled) {
          if (!user.twoFactorSecret) {
            // Defensive: flag says enabled, secret missing — treat as not
            // verifiable and reject. Surfaces as generic failure so an
            // attacker can't distinguish this configuration state.
            await logSecurityEvent({
              eventType: "LOGIN_FAILED",
              severity: "WARNING",
              userId: user.id,
              email: user.email,
              details: { reason: "2fa_enabled_but_no_secret" },
            });
            return null;
          }
          const totp = typeof credentials.totp === "string" ? credentials.totp.trim() : "";
          if (!totp) {
            await logSecurityEvent({
              eventType: "LOGIN_FAILED",
              severity: "INFO",
              userId: user.id,
              email: user.email,
              details: { reason: "2fa_required" },
            });
            throw new Error("2FA_REQUIRED");
          }
          if (!verifyTotp(user.twoFactorSecret, totp)) {
            await logSecurityEvent({
              eventType: "LOGIN_FAILED",
              severity: "WARNING",
              userId: user.id,
              email: user.email,
              details: { reason: "2fa_invalid" },
            });
            throw new Error("2FA_INVALID");
          }
        }

        return {
          id: user.id,
          email: user.email,
          name: user.name,
          image: user.image,
          role: user.role,
        };
      },
    }),
  ],
  session: {
    strategy: "jwt",
  },
  events: {
    // RA-1259: the PrismaAdapter `createUser` event fires only when the
    // OAuth provider creates a brand-new User row (i.e. no email match
    // existed). Flag them so the dashboard middleware redirects to
    // /onboarding/account-type until the required AU business fields
    // (ABN/ACN/state/business name) are captured. Credentials signups
    // do NOT hit this — they run through /api/auth/register which
    // already collects these fields.
    async createUser({ user }) {
      try {
        await prisma.user.update({
          where: { id: user.id },
          data: {
            needsOnboarding: true,
            role: "ADMIN",
            subscriptionStatus: "TRIAL",
            creditsRemaining: 30,
            totalCreditsUsed: 0,
            trialEndsAt: new Date(Date.now() + 30 * 24 * 60 * 60 * 1000),
            quickFillCreditsRemaining: 30,
            totalQuickFillUsed: 0,
          } as any,
        });
      } catch (err) {
        console.error(
          "[auth.createUser] failed to flag OAuth signup:",
          err instanceof Error ? err.message : String(err),
        );
      }
    },
  },
  callbacks: {
    async jwt({ token, user, trigger }) {
      if (user) {
        token.role = (user as { role?: string }).role ?? "";
      }
      // RA-1259: keep `needsOnboarding` fresh on first mint and after the
      // client calls `update()` post-onboarding so middleware stops
      // redirecting once the user completes the form.
      const shouldRefresh =
        Boolean(user) ||
        trigger === "update" ||
        (token as any).needsOnboarding === undefined;
      if (token.sub && shouldRefresh) {
        try {
          const fresh = await prisma.user.findUnique({
            where: { id: token.sub },
            select: { needsOnboarding: true } as any,
          });
          (token as any).needsOnboarding = Boolean(
            (fresh as any)?.needsOnboarding,
          );
        } catch {
          (token as any).needsOnboarding = false;
        }
      }
      return token;
    },
    async session({ session, token }) {
      if (token && session.user) {
        session.user.id = token.sub!;
        session.user.role = token.role as string;
        (session.user as any).needsOnboarding = Boolean(
          (token as any).needsOnboarding,
        );
      }
      return session;
    },
  },
  pages: {
    signIn: "/login",
  },
  secret: process.env.NEXTAUTH_SECRET,
};
