import { NextAuthOptions } from "next-auth";
import { PrismaAdapter } from "@next-auth/prisma-adapter";
import { encryptAccountTokens } from "@/lib/auth/account-tokens";
import GoogleProvider from "next-auth/providers/google";
import AppleProvider from "next-auth/providers/apple";
import CredentialsProvider from "next-auth/providers/credentials";
import { prisma } from "./prisma";
import bcrypt from "bcryptjs";
import crypto from "crypto";
import jwt from "jsonwebtoken";
import { readTotpSecret } from "@/lib/auth/totp-secret";
import {
  verifyToken as verifyTotp,
  parseRecoveryCodes,
  serializeRecoveryCodes,
  consumeRecoveryCode,
  looksLikeRecoveryCode,
} from "./auth/two-factor";
import { logSecurityEvent, getAccountLockoutStatus } from "./security-audit";
import { TRIAL_DAYS } from "@/lib/billing/constants";
import { PRICING_CONFIG } from "@/lib/pricing";
import { canonicalEmail, lockEmailIdentity } from "@/lib/email-identity";

const SESSION_REVOCATION_RECHECK_SECONDS = 24 * 60 * 60;
const SESSION_REVOCATION_RETRY_SECONDS = 5 * 60;

/**
 * Verify an HMAC token generated by /api/auth/google-signin. Max age: 5 minutes.
 *
 * Exported so /api/auth/google-session can demand the same proof-of-Google-auth
 * before disclosing any user data (enumeration guard — RA-6940).
 */
export function verifyGoogleAuthToken(email: string, token: string): boolean {
  try {
    const secret = process.env.NEXTAUTH_SECRET;
    if (!secret) return false;
    const parts = token.split(":");
    if (parts.length !== 3 || parts[0] !== "gauth") return false;
    const [, timestamp, hmac] = parts;
    const age = Date.now() - parseInt(timestamp, 10);
    if (age > 5 * 60 * 1000 || age < 0) return false; // expired or future-dated
    const expected = crypto
      .createHmac("sha256", secret)
      .update(`gauth:${email}:${timestamp}`)
      .digest("hex");
    return crypto.timingSafeEqual(
      Buffer.from(hmac, "hex"),
      Buffer.from(expected, "hex"),
    );
  } catch {
    return false;
  }
}

// B3: encrypt OAuth tokens at rest. Wrap PrismaAdapter.linkAccount so Google
// access/refresh/id tokens are ciphertexted before they reach the Account table.
const basePrismaAdapter = PrismaAdapter(prisma);
const encryptingPrismaAdapter = {
  ...basePrismaAdapter,
  createUser: async (data: any) => {
    const email = canonicalEmail(data.email);
    return prisma.$transaction(async (tx) => {
      await lockEmailIdentity(tx, email);
      const activeInvite = await tx.userInvite.findFirst({
        where: {
          email: { equals: email, mode: "insensitive" },
          usedAt: null,
          expiresAt: { gt: new Date() },
        },
        select: { id: true },
      });
      if (activeInvite) {
        // OAuth needs a database identity before NextAuth can persist the
        // provider Account and establish the session used by invite Step 2.
        // Create only a non-owner, unassigned identity here. The invitation
        // claim transaction is the sole place that can attach the organisation
        // and role; no trial, credits, subscription or owner entitlement is
        // granted at this boundary.
        return tx.user.create({
          data: {
            ...data,
            email,
            role: "USER",
            organizationId: null,
            subscriptionStatus: null,
            subscriptionPlan: null,
            subscriptionId: null,
            stripeCustomerId: null,
            trialEndsAt: null,
            subscriptionEndsAt: null,
            creditsRemaining: null,
            totalCreditsUsed: 0,
            quickFillCreditsRemaining: null,
            totalQuickFillUsed: 0,
            signupBonusApplied: false,
            needsOnboarding: true,
            pendingInviteIdentity: true,
          },
        });
      }
      return tx.user.create({ data: { ...data, email } });
    });
  },
  linkAccount: (account: any) =>
    basePrismaAdapter.linkAccount!(encryptAccountTokens(account)),
};

export const authOptions: NextAuthOptions = {
  adapter: encryptingPrismaAdapter as any,
  providers: [
    GoogleProvider({
      clientId: process.env.GOOGLE_CLIENT_ID!,
      clientSecret: process.env.GOOGLE_CLIENT_SECRET!,
      // RA-2119 Cause 4 — let a credentials user who later taps "Continue
      // with Google" link the Google account to their existing User row
      // instead of throwing OAuthAccountNotLinked and looping back to the
      // login page. Google verifies email ownership, so this is safe for
      // first-party email matching.
      allowDangerousEmailAccountLinking: true,
    }),
    // RA-1842 Ground 2 — Sign in with Apple (Apple guideline 4.8).
    // Required by App Review because the app offers third-party login.
    // Provider is registered conditionally so missing env vars don't
    // crash the auth handler in dev / preview deploys without the
    // Apple Developer config in place yet.
    //
    // Apple's "client secret" is a JWT signed with the .p8 private
    // key. We pass it via APPLE_CLIENT_SECRET — the deploy infra is
    // responsible for generating + rotating the JWT (typical ttl: 6 mo).
    // See docs/IOS_SIGN_IN_WITH_APPLE.md for the rotation runbook.
    ...(process.env.APPLE_CLIENT_ID && process.env.APPLE_CLIENT_SECRET
      ? [
          AppleProvider({
            clientId: process.env.APPLE_CLIENT_ID,
            clientSecret: process.env.APPLE_CLIENT_SECRET,
            // RA-2119 Cause 4 — same rationale as Google above. Apple
            // verifies email ownership (private-relay or real-mail) so
            // linking the Apple account to an existing credentials User
            // by email is safe and prevents the OAuthAccountNotLinked
            // loop on the iOS native Sign in with Apple flow.
            allowDangerousEmailAccountLinking: true,
          }),
        ]
      : []),
    CredentialsProvider({
      name: "credentials",
      credentials: {
        email: { label: "Email", type: "email" },
        password: { label: "Password", type: "password" },
        // RA-1587 — second-factor code. Required only when the account
        // has `twoFactorEnabled=true`. The login page collects it after
        // a `2FA_REQUIRED` error bounces the first submission.
        totp: { label: "6-digit authenticator code", type: "text" },
        // RA-2074 — "Stay signed in" toggle from the login form. When
        // "true" the JWT is stamped with a 90-day customExp instead of
        // the default 7-day. Field technicians on iOS need long-lived
        // sessions so they don't re-auth between shifts.
        rememberMe: { label: "Stay signed in", type: "text" },
      },
      async authorize(credentials) {
        if (!credentials?.email || !credentials?.password) {
          return null;
        }

        // Keep the submitted spelling for the short-lived Google HMAC: the
        // email is part of the signed payload, so changing it before
        // verification would invalidate an authentic token. Database identity,
        // lockout accounting and audit events use the canonical representation.
        const submittedEmail = credentials.email;
        const email = canonicalEmail(submittedEmail);

        // RA-1590 — account lockout. Check BEFORE user lookup leaks the
        // "account exists" timing difference. Using email here means a
        // targeted attacker gets locked out per-victim regardless of
        // whether the email is a real user. Fail-open on DB error so a
        // Prisma blip doesn't denial-of-service every login.
        const preLockout = await getAccountLockoutStatus({
          email,
        });
        if (preLockout.locked) {
          throw new Error(
            `ACCOUNT_LOCKED:${preLockout.retryAfterSeconds ?? 900}`,
          );
        }

        const user = await prisma.user.findUnique({
          where: { email },
        });

        if (!user) {
          await logSecurityEvent({
            eventType: "LOGIN_FAILED",
            severity: "INFO",
            email,
            details: { reason: "user_not_found" },
          });
          return null;
        }

        // Google sign-in path: password field carries a short-lived HMAC proof token.
        // 2FA still enforced on top — the short-lived HMAC proves the Google callback,
        // not a standing authentication.
        const isGoogleAuth = credentials.password.startsWith("gauth:");
        if (isGoogleAuth) {
          if (!verifyGoogleAuthToken(submittedEmail, credentials.password)) {
            await logSecurityEvent({
              eventType: "LOGIN_FAILED",
              severity: "WARNING",
              userId: user.id,
              email: user.email,
              details: { reason: "google_hmac_invalid" },
            });
            return null;
          }
        } else {
          if (!user.password) {
            await logSecurityEvent({
              eventType: "LOGIN_FAILED",
              severity: "INFO",
              userId: user.id,
              email: user.email,
              details: { reason: "no_password_on_file" },
            });
            return null;
          }
          const isPasswordValid = await bcrypt.compare(
            credentials.password,
            user.password,
          );
          if (!isPasswordValid) {
            await logSecurityEvent({
              eventType: "LOGIN_FAILED",
              severity: "WARNING",
              userId: user.id,
              email: user.email,
              details: { reason: "bad_password" },
            });
            return null;
          }
        }

        // RA-1587 — enforce TOTP when the account has 2FA enabled.
        // The prior `authorize()` returned a session as soon as the
        // password matched, making the "2FA enabled" flag purely
        // cosmetic. We now require a valid TOTP on every login when
        // `twoFactorEnabled` is true — including the Google-signin
        // path, so a compromised Google account still can't log in
        // without the authenticator.
        //
        // NextAuth CredentialsProvider surfaces thrown errors as
        // `?error=<message>` on the callback URL. The login page
        // treats `2FA_REQUIRED` as "show the TOTP field" and
        // `2FA_INVALID` as "wrong code".
        if (user.twoFactorEnabled) {
          if (!user.twoFactorSecret) {
            // Defensive: flag says enabled, secret missing — treat as not
            // verifiable and reject. Surfaces as generic failure so an
            // attacker can't distinguish this configuration state.
            await logSecurityEvent({
              eventType: "LOGIN_FAILED",
              severity: "WARNING",
              userId: user.id,
              email: user.email,
              details: { reason: "2fa_enabled_but_no_secret" },
            });
            return null;
          }
          const totp =
            typeof credentials.totp === "string" ? credentials.totp.trim() : "";
          if (!totp) {
            await logSecurityEvent({
              eventType: "LOGIN_FAILED",
              severity: "INFO",
              userId: user.id,
              email: user.email,
              details: { reason: "2fa_required" },
            });
            throw new Error("2FA_REQUIRED");
          }

          // RA-1588 — accept recovery codes in the same TOTP field.
          // Heuristic parses shape: 6 digits = TOTP; anything
          // matching XXXXX-XXXXX = recovery code. Consuming a
          // recovery code spliced-removes it from the stored array
          // so each is single-use.
          if (looksLikeRecoveryCode(totp)) {
            const storedHashes = parseRecoveryCodes(
              (user as { twoFactorRecoveryCodes?: string | null })
                .twoFactorRecoveryCodes,
            );
            if (storedHashes.length === 0) {
              await logSecurityEvent({
                eventType: "LOGIN_FAILED",
                severity: "WARNING",
                userId: user.id,
                email: user.email,
                details: { reason: "2fa_recovery_no_codes_enrolled" },
              });
              throw new Error("2FA_INVALID");
            }
            const remaining = await consumeRecoveryCode(totp, storedHashes);
            if (!remaining) {
              await logSecurityEvent({
                eventType: "LOGIN_FAILED",
                severity: "WARNING",
                userId: user.id,
                email: user.email,
                details: { reason: "2fa_recovery_invalid" },
              });
              throw new Error("2FA_INVALID");
            }
            const consumed = await prisma.user.updateMany({
              where: {
                id: user.id,
                twoFactorRecoveryCodes:
                  (user as { twoFactorRecoveryCodes?: string | null })
                    .twoFactorRecoveryCodes ?? null,
              },
              data: {
                twoFactorRecoveryCodes: serializeRecoveryCodes(remaining),
              } as any,
            });
            if (consumed.count !== 1) {
              // Another login consumed this snapshot first. Refuse this
              // claimant rather than issuing two sessions for one recovery
              // code.
              throw new Error("2FA_INVALID");
            }
            await logSecurityEvent({
              eventType: "LOGIN_SUCCESS",
              severity: "WARNING", // recovery-code use is noteworthy, not fatal
              userId: user.id,
              email: user.email,
              details: {
                method: "2fa_recovery_code",
                remainingCodes: remaining.length,
              },
            });
          } else if (!verifyTotp(readTotpSecret(user.twoFactorSecret), totp)) {
            await logSecurityEvent({
              eventType: "LOGIN_FAILED",
              severity: "WARNING",
              userId: user.id,
              email: user.email,
              details: { reason: "2fa_invalid" },
            });
            throw new Error("2FA_INVALID");
          }
        }

        // RA-2074 — propagate the rememberMe flag from the form into
        // the User object so jwt() can read it and stamp the right
        // customExp. Defaults to false when the form omits it (e.g.
        // older clients) so we don't accidentally extend sessions.
        const rememberMe = credentials.rememberMe === "true";

        return {
          id: user.id,
          email: user.email,
          name: user.name,
          image: user.image,
          role: user.role,
          rememberMe,
        } as any;
      },
    }),
  ],
  // RA-1593 — session hardening.
  // RA-2074 — stay-signed-in.
  //   - `maxAge: 90d` — UPPER bound on session length. The actual
  //     boundary for any given user is enforced by `customExp` stamped
  //     in jwt() based on whether they ticked "Stay signed in":
  //       * rememberMe = false  →  customExp = now + 7d  (old default)
  //       * rememberMe = true   →  customExp = now + 90d
  //       * OAuth (Google/Apple) → customExp = now + 90d (no checkbox shown)
  //     The session() callback validates against customExp and refuses
  //     to return a session past it.
  //   - `updateAge: 24h` — JWT cookie rotation remains bounded. Global
  //     revocation uses its own `revocationCheckedAt` timestamp below,
  //     because NextAuth does not pass trigger="update" for routine JWT
  //     session reads.
  //   - cookie block — explicit `maxAge` matches `session.maxAge` so
  //     WKWebView writes a persistent cookie (with Expires/Max-Age) and
  //     not a session cookie. Without this, force-quitting the iOS app
  //     was purging the session-token before the JWT expired. The
  //     `__Secure-` prefix in prod is browser-enforced HTTPS-only.
  session: {
    strategy: "jwt",
    maxAge: 90 * 24 * 60 * 60,
    updateAge: 24 * 60 * 60,
  },
  cookies: {
    sessionToken: {
      name:
        process.env.NODE_ENV === "production"
          ? "__Secure-next-auth.session-token"
          : "next-auth.session-token",
      options: {
        httpOnly: true,
        sameSite: "lax",
        path: "/",
        secure: process.env.NODE_ENV === "production",
        maxAge: 90 * 24 * 60 * 60,
      },
    },
  },
  events: {
    // RA-1259: the PrismaAdapter `createUser` event fires only when the
    // OAuth provider creates a brand-new User row (i.e. no email match
    // existed). Flag them so the dashboard middleware redirects to
    // /onboarding/account-type until the required AU business fields
    // (ABN/ACN/state/business name) are captured. Credentials signups
    // do NOT hit this — they run through /api/auth/register which
    // already collects these fields.
    async createUser({ user }) {
      try {
        if ((user as { pendingInviteIdentity?: boolean }).pendingInviteIdentity === true) {
          // adapter.createUser deliberately created a powerless identity so
          // NextAuth can link the provider Account. Only invite acceptance may
          // grant an organisation and role. Persisted user state is authoritative;
          // re-querying an expiring invite here creates a privilege race.
          return;
        }
        await prisma.user.update({
          where: { id: user.id },
          data: {
            needsOnboarding: true,
            role: "ADMIN",
            subscriptionStatus: "TRIAL",
            // Same grant as /api/auth/register — never hardcode beside PRICING_CONFIG.
            creditsRemaining: PRICING_CONFIG.free.trialReportCredits,
            totalCreditsUsed: 0,
            trialEndsAt: new Date(
              Date.now() + TRIAL_DAYS * 24 * 60 * 60 * 1000,
            ),
            quickFillCreditsRemaining:
              PRICING_CONFIG.free.trialQuickFillCredits,
            totalQuickFillUsed: 0,
          } as any,
        });
      } catch (err) {
        console.error(
          "[auth.createUser] failed to flag OAuth signup:",
          err instanceof Error ? err.message : String(err),
        );
      }
    },
  },
  callbacks: {
    async signIn({ user, account }) {
      if (account?.provider && account.provider !== "credentials") {
        const existing = user.id
          ? await prisma.user.findUnique({
              where: { id: user.id },
              select: { twoFactorEnabled: true },
            })
          : user.email
            ? await prisma.user.findUnique({
                where: { email: canonicalEmail(user.email) },
                select: { twoFactorEnabled: true },
              })
            : null;
        if (existing?.twoFactorEnabled) {
          // OAuth proves the provider identity, not RestoreAssist's enrolled
          // second factor. Refuse direct OAuth until a server-verified TOTP
          // handoff exists; the credentials login provides that challenge.
          return "/login?error=2FA_REQUIRED";
        }
      }
      return true;
    },
    async jwt({ token, user, trigger, account }) {
      if (user) {
        token.role = (user as { role?: string }).role ?? "";
        // Stamp the mint time so the revoke check below has a `since`
        // anchor to compare against — `iat` is not always on the
        // NextAuth token type in TS so we track it ourselves.
        (token as any).mintedAt = Math.floor(Date.now() / 1000);

        // RA-2074 — stamp customExp based on rememberMe. CredentialsProvider
        // forwards the form's checkbox via `user.rememberMe`. OAuth
        // providers (Google / Apple) don't show a checkbox so we default
        // them to the long lifetime — once a user grants OAuth consent
        // it's reasonable to honour that for 90 days.
        const isOAuth = account?.provider && account.provider !== "credentials";
        const remember = isOAuth || (user as any).rememberMe === true;
        const lifetimeSeconds = remember ? 90 * 24 * 60 * 60 : 7 * 24 * 60 * 60;
        (token as any).rememberMe = remember;
        (token as any).customExp =
          Math.floor(Date.now() / 1000) + lifetimeSeconds;
      }
      // RA-1259: keep `needsOnboarding` fresh on first mint, after the
      // client calls `update()`, and while the gate is still closed.
      // Middleware reads getToken() and cannot see the DB. A stale
      // `true` claim after POST /api/onboarding/account-type therefore
      // bounced every /dashboard click back to the form. Routine
      // session GETs do not pass trigger="update", so we re-query
      // whenever the cookie still says the user needs onboarding.
      const shouldRefresh =
        Boolean(user) ||
        trigger === "update" ||
        (token as any).needsOnboarding === undefined ||
        (token as any).needsOnboarding === true;
      if (token.sub && shouldRefresh) {
        try {
          const fresh = await prisma.user.findUnique({
            where: { id: token.sub },
            select: { needsOnboarding: true, role: true } as any,
          });
          (token as any).needsOnboarding = Boolean(
            (fresh as any)?.needsOnboarding,
          );
          // RA-1593 — privilege-change rotation. If the DB role no
          // longer matches the token, bump the mint time so downstream
          // permission checks pick up the new role immediately. A
          // demotion cannot be papered over by a stale JWT.
          const dbRole = (fresh as any)?.role ?? "";
          if (dbRole && token.role !== dbRole) {
            token.role = dbRole;
            (token as any).mintedAt = Math.floor(Date.now() / 1000);
          }
        } catch {
          (token as any).needsOnboarding = false;
        }
      }

      // RA-4984 — stamp subscription claims so middleware can enforce
      // hard-paywall in edge runtime without Prisma. Refresh on signIn,
      // explicit update(), or when any required claim is missing. The
      // 24h JWT updateAge bounds staleness in steady state; webhook
      // handlers (Stripe checkout.completed, subscription.deleted) call
      // session().update() to force-refresh after a billing transition.
      if (
        token.sub &&
        (trigger === "signIn" ||
          trigger === "update" ||
          (token as any).subscriptionStatus === undefined)
      ) {
        try {
          const userSub = await prisma.user.findUnique({
            where: { id: token.sub as string },
            select: {
              subscriptionStatus: true,
              trialEndsAt: true,
              lifetimeAccess: true,
            },
          });
          token.subscriptionStatus = userSub?.subscriptionStatus ?? null;
          token.trialEndsAt = userSub?.trialEndsAt
            ? userSub.trialEndsAt.toISOString()
            : null;
          token.lifetimeAccess = userSub?.lifetimeAccess ?? null;
        } catch {
          // Fail-open — a DB blip should not log every user out. Stamp
          // a permissive default; middleware will treat missing-status
          // as allow, and the API-route gate (CLAUDE.md rule #5) still
          // enforces revenue protection authoritatively.
          token.subscriptionStatus = token.subscriptionStatus ?? null;
          token.trialEndsAt = token.trialEndsAt ?? null;
          token.lifetimeAccess = token.lifetimeAccess ?? null;
        }
      }

      // C2+C5: keep setupCompletedAt fresh. Refresh when missing OR null so
      // that invited admins (who have organizationId but aren't the owner)
      // and users whose org gets activated mid-session both pick up the
      // correct value without waiting up to 24h for JWT updateAge.
      if (
        token.sub &&
        (trigger === "signIn" ||
          trigger === "update" ||
          (token as any).setupCompletedAt == null)
      ) {
        try {
          const userWithOrg = await prisma.user.findUnique({
            where: { id: token.sub as string },
            select: { organization: { select: { setupCompletedAt: true } } },
          });
          const setupCompletedAt = (userWithOrg as any)?.organization
            ?.setupCompletedAt;
          (token as any).setupCompletedAt = setupCompletedAt
            ? (setupCompletedAt as Date).toISOString()
            : null;
        } catch {
          // Fail-open — don't break auth on a transient DB error.
          if (!("setupCompletedAt" in token)) {
            (token as any).setupCompletedAt = null;
          }
        }
      }

      // RA-1593 — global revoke. Keep stateless JWT behaviour between checks,
      // but do not rely on NextAuth's updateAge: JWT session reads do not emit
      // trigger="update" during routine cookie rotation. Persist the last
      // successful check time in the token and re-query after 24 hours.
      const nowSeconds = Math.floor(Date.now() / 1000);
      const rawRevocationCheckedAt = (token as any).revocationCheckedAt;
      const revocationCheckedAt =
        typeof rawRevocationCheckedAt === "number" &&
        Number.isFinite(rawRevocationCheckedAt)
          ? rawRevocationCheckedAt
          : null;
      const rawRevocationRetryAt = (token as any).revocationRetryAt;
      const revocationRetryAt =
        typeof rawRevocationRetryAt === "number" &&
        Number.isFinite(rawRevocationRetryAt)
          ? rawRevocationRetryAt
          : null;
      const shouldCheckRevocation =
        trigger === "update" ||
        (revocationRetryAt !== null
          ? revocationRetryAt <= nowSeconds ||
            revocationRetryAt > nowSeconds + SESSION_REVOCATION_RETRY_SECONDS
          : revocationCheckedAt === null ||
            revocationCheckedAt > nowSeconds ||
            nowSeconds - revocationCheckedAt >=
              SESSION_REVOCATION_RECHECK_SECONDS);

      if (token.sub && shouldCheckRevocation) {
        try {
          const revokeEvent = await prisma.securityEvent.findFirst({
            where: {
              userId: token.sub,
              eventType: "SESSIONS_REVOKED",
            },
            orderBy: { createdAt: "desc" },
            select: { createdAt: true },
          });
          if (revokeEvent) {
            const mintedAt =
              typeof (token as any).mintedAt === "number"
                ? (token as any).mintedAt
                : typeof token.iat === "number"
                  ? token.iat
                  : null;
            const revokedAt = Math.floor(
              revokeEvent.createdAt.getTime() / 1000,
            );
            if (mintedAt === null || revokedAt >= mintedAt) {
              // Return a token shape NextAuth will refuse to serialise
              // into a session — the next session() callback sees no
              // userId and middleware redirects to /login.
              return { ...token, sub: undefined, revoked: true } as any;
            }
          }
          (token as any).revocationCheckedAt = nowSeconds;
          delete (token as any).revocationRetryAt;
        } catch {
          // Fail-open on transient Prisma error — a DB blip should not
          // log every user out. Retry after five minutes rather than on every
          // request or postponing the check for another full day.
          (token as any).revocationRetryAt =
            nowSeconds + SESSION_REVOCATION_RETRY_SECONDS;
        }
      }

      return token;
    },
    async session({ session, token }) {
      // RA-2074 — enforce customExp. session.maxAge is the UPPER bound
      // (90d). The actual session length per user comes from customExp
      // which is 7d for default logins and 90d when rememberMe ticked.
      // Past customExp we strip user identity so middleware redirects.
      const customExp = (token as any).customExp;
      if (
        typeof customExp === "number" &&
        Math.floor(Date.now() / 1000) > customExp
      ) {
        return { ...session, user: undefined } as any;
      }
      if (token && session.user) {
        session.user.id = token.sub!;
        session.user.role = token.role as string;
        (session.user as any).needsOnboarding = Boolean(
          (token as any).needsOnboarding,
        );
      }
      return session;
    },
  },
  pages: {
    signIn: "/login",
  },
  secret: process.env.NEXTAUTH_SECRET,
};
