export const mockClients = [
  {
    id: "1",
    name: "Advanced Property Restoration",
    email: "contact@advancedprop.com.au",
    phone: "+61 2 9876 5432",
    address: "123 Restoration Ave, Sydney NSW 2000",
    reports: 45,
    revenue: "$225,000",
    lastJob: "2 hours ago",
    status: "active",
  },
  {
    id: "2",
    name: "Restore Pro QLD",
    email: "info@restorepro.com.au",
    phone: "+61 7 3456 7890",
    address: "456 Repair St, Brisbane QLD 4000",
    reports: 32,
    revenue: "$156,800",
    lastJob: "5 hours ago",
    status: "active",
  },
  {
    id: "3",
    name: "Impact Restoration Services",
    email: "hello@impactrest.com.au",
    phone: "+61 3 9876 5432",
    address: "789 Recovery Rd, Melbourne VIC 3000",
    reports: 28,
    revenue: "$142,400",
    lastJob: "1 day ago",
    status: "active",
  },
  {
    id: "4",
    name: "Clean Slate Services",
    email: "support@cleanslate.com.au",
    phone: "+61 8 9876 5432",
    address: "321 Fresh Lane, Perth WA 6000",
    reports: 18,
    revenue: "$91,200",
    lastJob: "2 days ago",
    status: "active",
  },
]

export const mockReports = [
  {
    id: "WD-2025-001",
    clientId: "1",
    clientName: "Advanced Property Restoration",
    hazard: "Water",
    status: "Approved",
    cost: "$12,500",
    date: "2 hours ago",
    property: "123 Main St, Sydney NSW",
    insurer: "QBE Insurance",
    policyType: "Building & Contents",
    completionTime: "2.5 hours",
  },
  {
    id: "FD-2025-002",
    clientId: "2",
    clientName: "Restore Pro QLD",
    hazard: "Fire",
    status: "Pending",
    cost: "$8,750",
    date: "5 hours ago",
    property: "456 Oak Ave, Brisbane QLD",
    insurer: "Allianz",
    policyType: "Landlord Insurance",
    completionTime: "1.8 hours",
  },
  {
    id: "SD-2025-003",
    clientId: "3",
    clientName: "Impact Restoration",
    hazard: "Storm",
    status: "In Progress",
    cost: "$15,200",
    date: "1 day ago",
    property: "789 Elm St, Melbourne VIC",
    insurer: "NRMA",
    policyType: "Standalone Building",
    completionTime: "3.2 hours",
  },
  {
    id: "MD-2025-004",
    clientId: "4",
    clientName: "Clean Slate Services",
    hazard: "Mould",
    status: "Approved",
    cost: "$6,300",
    date: "2 days ago",
    property: "321 Pine Rd, Perth WA",
    insurer: "Westpac",
    policyType: "Standalone Contents",
    completionTime: "1.5 hours",
  },
]

export const mockCostLibraries = [
  {
    id: "1",
    name: "Sydney Metro",
    region: "NSW",
    isDefault: true,
    items: [
      { category: "Labor", description: "Water Extraction (per hour)", rate: "$150", unit: "hour" },
      { category: "Labor", description: "Drying & Dehumidification", rate: "$120", unit: "hour" },
      { category: "Materials", description: "Dehumidifier Rental", rate: "$45", unit: "day" },
      { category: "Equipment", description: "Air Mover", rate: "$35", unit: "day" },
    ],
  },
  {
    id: "2",
    name: "Brisbane Metro",
    region: "QLD",
    isDefault: false,
    items: [
      { category: "Labor", description: "Water Extraction (per hour)", rate: "$140", unit: "hour" },
      { category: "Labor", description: "Drying & Dehumidification", rate: "$110", unit: "hour" },
      { category: "Materials", description: "Dehumidifier Rental", rate: "$40", unit: "day" },
      { category: "Equipment", description: "Air Mover", rate: "$30", unit: "day" },
    ],
  },
]

export const mockIntegrations = [
  {
    id: "1",
    name: "Ascora CRM",
    description: "Bi-directional sync with Ascora CRM",
    status: "connected",
    icon: "🔗",
  },
  {
    id: "2",
    name: "Anthropic Claude",
    description: "AI-powered report generation",
    status: "connected",
    icon: "🤖",
  },
  {
    id: "3",
    name: "OpenAI GPT",
    description: "Alternative AI provider",
    status: "disconnected",
    icon: "🧠",
  },
  {
    id: "4",
    name: "DocuSign",
    description: "Electronic signature integration",
    status: "connected",
    icon: "✍️",
  },
  {
    id: "5",
    name: "Stripe",
    description: "Payment processing",
    status: "disconnected",
    icon: "💳",
  },
  {
    id: "6",
    name: "Bureau of Meteorology",
    description: "Weather data integration",
    status: "connected",
    icon: "🌦️",
  },
]
