/**
 * Reads scripts/prod-drift-fix.sql (generated by prisma migrate diff)
 * and writes scripts/prod-drift-fix-SAFE.sql containing ONLY additive,
 * idempotent operations that bring missing schema elements into prod
 * WITHOUT touching anything that already exists.
 *
 * Discarded (unsafe):
 *   - DROP TABLE / DROP INDEX / DROP TYPE / DROP CONSTRAINT
 *   - ALTER TABLE DROP COLUMN
 *   - ALTER TABLE ALTER COLUMN (type changes)
 *   - BEGIN/COMMIT enum-rotation blocks (which DROP and recreate enums)
 *   - Any statement touching the "auth" schema (Supabase manages it)
 *
 * Kept (safe additive):
 *   - CREATE TABLE → rewritten as CREATE TABLE IF NOT EXISTS
 *   - CREATE INDEX → rewritten as CREATE INDEX IF NOT EXISTS
 *   - CREATE TYPE → wrapped in DO block with IF NOT EXISTS check (Postgres has no
 *                   native CREATE TYPE IF NOT EXISTS for enums)
 *   - ALTER TABLE ADD COLUMN → rewritten as ADD COLUMN IF NOT EXISTS
 *   - ALTER TABLE ADD CONSTRAINT FOREIGN KEY → wrapped in DO block guard
 *   - ALTER TYPE ADD VALUE (enum extension) → wrapped in DO block guard
 *
 * Run:
 *   npx tsx scripts/filter-drift-fix-additive-only.ts
 */

import * as fs from "fs";
import * as path from "path";

const scriptDir = path.dirname(new URL(import.meta.url).pathname);
const inFile = path.join(scriptDir, "prod-drift-fix.sql");
const outFile = path.join(scriptDir, "prod-drift-fix-SAFE.sql");

if (!fs.existsSync(inFile)) {
  console.error(`Input not found: ${inFile}`);
  console.error("Run scripts/generate-prod-drift-fix.ts first.");
  process.exit(1);
}

const raw = fs.readFileSync(inFile, "utf8");

// Split into top-level statements. Prisma's diff output uses blank lines and
// section comments (-- CreateTable, -- AddForeignKey, etc.) as separators.
// We split on blank lines AFTER also stripping BEGIN/COMMIT blocks separately.

interface Stmt {
  startLine: number;
  comment: string; // The "-- CreateTable" header line
  body: string; // The actual SQL (trimmed)
}

const lines = raw.split("\n");
const stmts: Stmt[] = [];
let i = 0;
while (i < lines.length) {
  const line = lines[i];
  // Skip blank lines
  if (line.trim() === "") {
    i++;
    continue;
  }
  // Section header
  if (line.startsWith("-- ")) {
    const startLine = i + 1;
    const comment = line;
    i++;
    // Skip continuation comments (multi-line headers)
    while (i < lines.length && lines[i].startsWith("-- ")) i++;
    // Skip blank lines between header and body
    while (i < lines.length && lines[i].trim() === "") i++;
    // Collect body until next blank line followed by another -- header
    const bodyLines: string[] = [];
    while (i < lines.length) {
      const l = lines[i];
      // Stop if we hit a blank line followed by a -- header
      if (
        l.trim() === "" &&
        i + 1 < lines.length &&
        lines[i + 1].startsWith("-- ")
      ) {
        break;
      }
      if (l.trim() === "" && i + 1 >= lines.length) break;
      bodyLines.push(l);
      i++;
    }
    stmts.push({
      startLine,
      comment,
      body: bodyLines.join("\n").trim(),
    });
  } else {
    // Body line without a preceding comment (rare). Eat it as its own stmt.
    stmts.push({ startLine: i + 1, comment: "-- (no header)", body: line });
    i++;
  }
}

console.log(`Parsed ${stmts.length} statements from input`);

const kept: string[] = [];
const discarded: string[] = [];

const safeHeaders = new Set([
  "-- CreateTable",
  "-- CreateIndex",
  "-- CreateEnum",
  "-- AddForeignKey",
  "-- RenameIndex",
]);

const unsafeHeaders = new Set([
  "-- AlterEnum", // includes destructive enum rotations (DROP TYPE old)
  "-- DropTable",
  "-- DropIndex",
  "-- DropEnum",
  "-- DropForeignKey",
  "-- AlterTable", // mixed bag — can include DROP COLUMN, ALTER COLUMN
]);

for (const s of stmts) {
  const headerKey = s.comment.split("\n")[0];

  // Hard discard: anything touching "auth" schema (Supabase manages)
  if (s.body.includes('"auth".') || s.body.includes('"auth".')) {
    discarded.push(
      `L${s.startLine} ${headerKey} (auth schema — Supabase managed)`,
    );
    continue;
  }

  // -- AlterTable is the most dangerous category. Inspect body.
  if (headerKey === "-- AlterTable") {
    const body = s.body;
    const hasDrop = /\bDROP\s+(COLUMN|CONSTRAINT)\b/i.test(body);
    const hasAlterCol = /\bALTER\s+COLUMN\b/i.test(body);
    const hasAddCol = /\bADD\s+COLUMN\b/i.test(body);

    // NEW: even if a block is mixed (ADD + DROP), extract just the ADD COLUMN
    // statements as separate safe statements. The DROP/ALTER parts go to discarded.
    if (hasAddCol && (hasDrop || hasAlterCol)) {
      // Parse the leading "ALTER TABLE "X" " prefix
      const tableMatch = body.match(/^ALTER\s+TABLE\s+"([^"]+)"\s/i);
      if (!tableMatch) {
        discarded.push(
          `L${s.startLine} ${headerKey} (mixed but couldn't parse table name)`,
        );
        continue;
      }
      const tableName = tableMatch[1];
      // Find each ADD COLUMN clause. They look like:
      //   ADD COLUMN "name" TYPE [DEFAULT ...] [NOT NULL]
      // and are comma-separated in a single ALTER TABLE statement.
      const addColRegex =
        /ADD\s+COLUMN\s+"([^"]+)"\s+([^,;]+?)(?=,\s*(?:ADD|DROP|ALTER)\s|;)/gi;
      const safeStmts: string[] = [];
      let match: RegExpExecArray | null;
      while ((match = addColRegex.exec(body)) !== null) {
        const colName = match[1];
        const colType = match[2].trim();
        safeStmts.push(
          `ALTER TABLE "${tableName}" ADD COLUMN IF NOT EXISTS "${colName}" ${colType};`,
        );
      }
      if (safeStmts.length > 0) {
        kept.push(
          `-- (filtered, extracted ADD COLUMNs from mixed) ${headerKey} L${s.startLine}\n${safeStmts.join("\n")}\n`,
        );
        discarded.push(
          `L${s.startLine} ${headerKey} (mixed: kept ${safeStmts.length} ADD COLUMN, dropped DROP/ALTER COLUMN parts)`,
        );
      } else {
        discarded.push(
          `L${s.startLine} ${headerKey} (mixed but couldn't parse ADD COLUMN clauses)`,
        );
      }
      continue;
    }

    if (hasDrop || hasAlterCol) {
      discarded.push(
        `L${s.startLine} ${headerKey} (contains DROP/ALTER COLUMN — destructive, no ADD COLUMN to salvage)`,
      );
      continue;
    }
    if (hasAddCol) {
      // Convert ADD COLUMN "x" ... → ADD COLUMN IF NOT EXISTS "x" ...
      const safe = body.replace(
        /\bADD COLUMN "([^"]+)"/g,
        'ADD COLUMN IF NOT EXISTS "$1"',
      );
      kept.push(`-- (filtered) ${headerKey} L${s.startLine}\n${safe}\n`);
      continue;
    }
    discarded.push(
      `L${s.startLine} ${headerKey} (unrecognised AlterTable shape)`,
    );
    continue;
  }

  // -- AlterEnum: only allow simple "ADD VALUE" forms; reject anything with
  // BEGIN/COMMIT (those are full enum rotations that DROP the old type).
  if (headerKey === "-- AlterEnum") {
    if (s.body.includes("BEGIN;")) {
      discarded.push(
        `L${s.startLine} ${headerKey} (full enum rotation — drops old type)`,
      );
      continue;
    }
    // Wrap each ADD VALUE in a DO guard
    const addValues = s.body.match(
      /ALTER TYPE "([^"]+)" ADD VALUE '([^']+)';/g,
    );
    if (!addValues || addValues.length === 0) {
      discarded.push(
        `L${s.startLine} ${headerKey} (unrecognised AlterEnum shape)`,
      );
      continue;
    }
    let safe = `-- (filtered) ${headerKey} L${s.startLine}\n`;
    for (const av of addValues) {
      const m = av.match(/ALTER TYPE "([^"]+)" ADD VALUE '([^']+)'/);
      if (!m) continue;
      const [, typeName, value] = m;
      safe += `DO $$ BEGIN
  IF NOT EXISTS (
    SELECT 1 FROM pg_enum WHERE enumlabel = '${value}'
    AND enumtypid = (SELECT oid FROM pg_type WHERE typname = '${typeName}')
  ) THEN
    ALTER TYPE "${typeName}" ADD VALUE '${value}';
  END IF;
END $$;\n`;
    }
    kept.push(safe);
    continue;
  }

  // Hard discard
  if (unsafeHeaders.has(headerKey)) {
    discarded.push(`L${s.startLine} ${headerKey}`);
    continue;
  }

  // Safe transformations
  if (headerKey === "-- CreateTable") {
    const safe = s.body.replace(
      /^CREATE TABLE "/m,
      'CREATE TABLE IF NOT EXISTS "',
    );
    kept.push(`-- (filtered) ${headerKey} L${s.startLine}\n${safe}\n`);
    continue;
  }
  if (headerKey === "-- CreateIndex") {
    // Both UNIQUE INDEX and INDEX
    const safe = s.body
      .replace(/^CREATE INDEX "/m, 'CREATE INDEX IF NOT EXISTS "')
      .replace(
        /^CREATE UNIQUE INDEX "/m,
        'CREATE UNIQUE INDEX IF NOT EXISTS "',
      );
    kept.push(`-- (filtered) ${headerKey} L${s.startLine}\n${safe}\n`);
    continue;
  }
  if (headerKey === "-- CreateEnum") {
    // CREATE TYPE x AS ENUM (...) — Postgres has no IF NOT EXISTS for types.
    // Wrap in DO block.
    const m = s.body.match(/CREATE TYPE "([^"]+)" AS ENUM \(([^)]*)\);?/);
    if (!m) {
      discarded.push(`L${s.startLine} ${headerKey} (could not parse)`);
      continue;
    }
    const [, name, values] = m;
    kept.push(
      `-- (filtered) ${headerKey} L${s.startLine}\nDO $$ BEGIN
  CREATE TYPE "${name}" AS ENUM (${values});
EXCEPTION WHEN duplicate_object THEN null;
END $$;\n`,
    );
    continue;
  }
  if (headerKey === "-- AddForeignKey") {
    // Wrap in DO block with constraint-exists guard
    const m = s.body.match(/ALTER TABLE "([^"]+)" ADD CONSTRAINT "([^"]+)"/);
    if (!m) {
      discarded.push(`L${s.startLine} ${headerKey} (could not parse)`);
      continue;
    }
    const [, table, constraint] = m;
    kept.push(
      `-- (filtered) ${headerKey} L${s.startLine}\nDO $$ BEGIN
  IF NOT EXISTS (
    SELECT 1 FROM pg_constraint WHERE conname = '${constraint}'
  ) THEN
    ${s.body}
  END IF;
END $$;\n`,
    );
    continue;
  }
  if (headerKey === "-- RenameIndex") {
    // Skip — these depend on the OLD index name existing, which is brittle
    discarded.push(
      `L${s.startLine} ${headerKey} (skipping rename — manual review needed)`,
    );
    continue;
  }

  discarded.push(`L${s.startLine} ${headerKey} (unrecognised)`);
}

// Write output
const header = `-- ================================================================
-- prod-drift-fix-SAFE.sql — additive-only, idempotent
-- Generated: ${new Date().toISOString()}
-- Source: prod-drift-fix.sql (filtered by filter-drift-fix-additive-only.ts)
--
-- Statements kept: ${kept.length}
-- Statements discarded: ${discarded.length}
--
-- Discarded log (review separately if anything unexpected):
${discarded.map((d) => `--   ${d}`).join("\n")}
-- ================================================================

`;

fs.writeFileSync(outFile, header + kept.join("\n"));
console.log(`\n✓ Wrote ${kept.length} safe statements to ${outFile}`);
console.log(
  `  Discarded ${discarded.length} unsafe statements (logged in file header)`,
);
console.log(`\nReview ${outFile} before running.`);
