-- ================================================================
-- fix-enum-values-first.sql
--
-- Adds missing enum values to existing prod enums so that the main
-- prod-drift-fix-SAFE.sql can succeed.
--
-- Postgres requires ALTER TYPE ADD VALUE to commit BEFORE the new
-- value can be used in the same transaction. So this runs first,
-- on its own.
--
-- Idempotent: each ADD VALUE uses IF NOT EXISTS.
-- Safe: never DROPs anything, never rotates an enum.
-- ================================================================

-- InterviewStatus expects: STARTED, IN_PROGRESS, COMPLETED, ABANDONED
ALTER TYPE "InterviewStatus" ADD VALUE IF NOT EXISTS 'STARTED';
ALTER TYPE "InterviewStatus" ADD VALUE IF NOT EXISTS 'IN_PROGRESS';
ALTER TYPE "InterviewStatus" ADD VALUE IF NOT EXISTS 'COMPLETED';
ALTER TYPE "InterviewStatus" ADD VALUE IF NOT EXISTS 'ABANDONED';

-- QuestionType expects: YES_NO, MULTIPLE_CHOICE, TEXT, NUMERIC, MEASUREMENT, LOCATION, MULTISELECT, CHECKBOX
ALTER TYPE "QuestionType" ADD VALUE IF NOT EXISTS 'YES_NO';
ALTER TYPE "QuestionType" ADD VALUE IF NOT EXISTS 'MULTIPLE_CHOICE';
ALTER TYPE "QuestionType" ADD VALUE IF NOT EXISTS 'TEXT';
ALTER TYPE "QuestionType" ADD VALUE IF NOT EXISTS 'NUMERIC';
ALTER TYPE "QuestionType" ADD VALUE IF NOT EXISTS 'MEASUREMENT';
ALTER TYPE "QuestionType" ADD VALUE IF NOT EXISTS 'LOCATION';
ALTER TYPE "QuestionType" ADD VALUE IF NOT EXISTS 'MULTISELECT';
ALTER TYPE "QuestionType" ADD VALUE IF NOT EXISTS 'CHECKBOX';

-- FormAuditAction expects: CREATED, FIELD_UPDATED, SAVED, SUBMITTED, SIGNATURE_ADDED, ATTACHMENT_ADDED, ATTACHMENT_REMOVED, STATUS_CHANGED, CANCELLED, REOPENED
ALTER TYPE "FormAuditAction" ADD VALUE IF NOT EXISTS 'CREATED';
ALTER TYPE "FormAuditAction" ADD VALUE IF NOT EXISTS 'FIELD_UPDATED';
ALTER TYPE "FormAuditAction" ADD VALUE IF NOT EXISTS 'SAVED';
ALTER TYPE "FormAuditAction" ADD VALUE IF NOT EXISTS 'SUBMITTED';
ALTER TYPE "FormAuditAction" ADD VALUE IF NOT EXISTS 'SIGNATURE_ADDED';
ALTER TYPE "FormAuditAction" ADD VALUE IF NOT EXISTS 'ATTACHMENT_ADDED';
ALTER TYPE "FormAuditAction" ADD VALUE IF NOT EXISTS 'ATTACHMENT_REMOVED';
ALTER TYPE "FormAuditAction" ADD VALUE IF NOT EXISTS 'STATUS_CHANGED';
ALTER TYPE "FormAuditAction" ADD VALUE IF NOT EXISTS 'CANCELLED';
ALTER TYPE "FormAuditAction" ADD VALUE IF NOT EXISTS 'REOPENED';

-- FormCategory expects: SAFETY, COMPLIANCE, CLIENT_INTAKE, JOB_DOCUMENTATION, INSURANCE, QUALITY_CONTROL, CUSTOM
ALTER TYPE "FormCategory" ADD VALUE IF NOT EXISTS 'SAFETY';
ALTER TYPE "FormCategory" ADD VALUE IF NOT EXISTS 'COMPLIANCE';
ALTER TYPE "FormCategory" ADD VALUE IF NOT EXISTS 'CLIENT_INTAKE';
ALTER TYPE "FormCategory" ADD VALUE IF NOT EXISTS 'JOB_DOCUMENTATION';
ALTER TYPE "FormCategory" ADD VALUE IF NOT EXISTS 'INSURANCE';
ALTER TYPE "FormCategory" ADD VALUE IF NOT EXISTS 'QUALITY_CONTROL';
ALTER TYPE "FormCategory" ADD VALUE IF NOT EXISTS 'CUSTOM';

-- FormSubmissionStatus expects: DRAFT, IN_PROGRESS, AWAITING_SIGNATURE, COMPLETED, CANCELLED, EXPIRED
ALTER TYPE "FormSubmissionStatus" ADD VALUE IF NOT EXISTS 'DRAFT';
ALTER TYPE "FormSubmissionStatus" ADD VALUE IF NOT EXISTS 'IN_PROGRESS';
ALTER TYPE "FormSubmissionStatus" ADD VALUE IF NOT EXISTS 'AWAITING_SIGNATURE';
ALTER TYPE "FormSubmissionStatus" ADD VALUE IF NOT EXISTS 'COMPLETED';
ALTER TYPE "FormSubmissionStatus" ADD VALUE IF NOT EXISTS 'CANCELLED';
ALTER TYPE "FormSubmissionStatus" ADD VALUE IF NOT EXISTS 'EXPIRED';

-- FormTemplateStatus expects: DRAFT, PUBLISHED, ARCHIVED, DEPRECATED
ALTER TYPE "FormTemplateStatus" ADD VALUE IF NOT EXISTS 'DRAFT';
ALTER TYPE "FormTemplateStatus" ADD VALUE IF NOT EXISTS 'PUBLISHED';
ALTER TYPE "FormTemplateStatus" ADD VALUE IF NOT EXISTS 'ARCHIVED';
ALTER TYPE "FormTemplateStatus" ADD VALUE IF NOT EXISTS 'DEPRECATED';

-- FormType expects: WORK_ORDER, AUTHORITY_TO_COMMENCE, JSA, SDS, SWIMS, SITE_INDUCTION, CUSTOM
ALTER TYPE "FormType" ADD VALUE IF NOT EXISTS 'WORK_ORDER';
ALTER TYPE "FormType" ADD VALUE IF NOT EXISTS 'AUTHORITY_TO_COMMENCE';
ALTER TYPE "FormType" ADD VALUE IF NOT EXISTS 'JSA';
ALTER TYPE "FormType" ADD VALUE IF NOT EXISTS 'SDS';
ALTER TYPE "FormType" ADD VALUE IF NOT EXISTS 'SWIMS';
ALTER TYPE "FormType" ADD VALUE IF NOT EXISTS 'SITE_INDUCTION';
ALTER TYPE "FormType" ADD VALUE IF NOT EXISTS 'CUSTOM';

-- SignatureType expects: DIGITAL_CANVAS, ELECTRONIC_TYPED, ESIGNATURE_WORKFLOW, BIOMETRIC
ALTER TYPE "SignatureType" ADD VALUE IF NOT EXISTS 'DIGITAL_CANVAS';
ALTER TYPE "SignatureType" ADD VALUE IF NOT EXISTS 'ELECTRONIC_TYPED';
ALTER TYPE "SignatureType" ADD VALUE IF NOT EXISTS 'ESIGNATURE_WORKFLOW';
ALTER TYPE "SignatureType" ADD VALUE IF NOT EXISTS 'BIOMETRIC';

-- EstimateStatus expects (per main diff additions): SENT, REJECTED, EXPIRED, WITHDRAWN
ALTER TYPE "EstimateStatus" ADD VALUE IF NOT EXISTS 'SENT';
ALTER TYPE "EstimateStatus" ADD VALUE IF NOT EXISTS 'REJECTED';
ALTER TYPE "EstimateStatus" ADD VALUE IF NOT EXISTS 'EXPIRED';
ALTER TYPE "EstimateStatus" ADD VALUE IF NOT EXISTS 'WITHDRAWN';

-- PaymentMethod expects: + EXTERNAL
ALTER TYPE "PaymentMethod" ADD VALUE IF NOT EXISTS 'EXTERNAL';

-- SignatoryRole expects: + PROPERTY_OWNER, CONTRACTOR
ALTER TYPE "SignatoryRole" ADD VALUE IF NOT EXISTS 'PROPERTY_OWNER';
ALTER TYPE "SignatoryRole" ADD VALUE IF NOT EXISTS 'CONTRACTOR';
