/**
 * NIR affected-area submission payload (RA-7001).
 *
 * The technician form stores each affected area's size in its
 * `affectedSquareFootage` state field, but that field is a misnomer: it holds
 * the area in **m²** (length × width in metres, rendered as "m²" in the UI).
 *
 * The /affected-areas route treats a bare `affectedSquareFootage` as square feet
 * and converts it (×0.09290304), which shrinks a genuine m² value ~10.76×. To
 * keep new rows correct we submit the value under the canonical `affectedAreaSqm`
 * key; the route then derives the deprecated sq-ft column via sqmToSqft for the
 * sq-ft-native IICRC classification engine.
 */
import { resolveAreaSqm } from "@/lib/units";
import { inferRoomTypeFromLabel } from "@/lib/forms/room-identity";

export interface NirAffectedAreaEntry {
  /** Stable draft row identity, retained across snapshot saves when present. */
  id?: string;
  roomZoneId: string;
  /** Misnomer: holds the area in m² (see module note). */
  affectedSquareFootage: number;
  waterSource: string;
  timeSinceLoss: number | null;
  length: number;
  width: number;
  height: number;
  materials: string[];
  /** Historical rows may have a different description format. Keep it intact. */
  originalDescription?: string | null;
  detailsKnown?: boolean;
}

/** Reopen a server row without treating its legacy square-foot value as m². */
export function hydrateAffectedAreaDraft(area: {
  id: string;
  roomZoneId: string;
  affectedAreaSqm?: number | null;
  affectedSquareFootage?: number | null;
  waterSource: string;
  timeSinceLoss?: number | null;
  description?: string | null;
  height?: number | null;
}) {
  // Only parse descriptions generated by this form. Other historical text
  // remains unknown rather than silently inventing dimensions or materials.
  const match = area.description?.match(
    /^Dimensions: (\d+(?:\.\d+)?)m × (\d+(?:\.\d+)?)m × (\d+(?:\.\d+)?)m\. Materials: ([^\n]+)(?:\n\nOriginal note: ([\s\S]*))?$/,
  );
  return {
    id: area.id,
    roomZoneId: area.roomZoneId,
    roomType: inferRoomTypeFromLabel(area.roomZoneId),
    length: match ? Number(match[1]) : 0,
    width: match ? Number(match[2]) : 0,
    height: match ? Number(match[3]) : (area.height ?? 0),
    affectedSquareFootage: resolveAreaSqm(area),
    materials: match ? match[4].split(", ").filter(Boolean) : [],
    waterSource: area.waterSource,
    timeSinceLoss: area.timeSinceLoss ?? null,
    originalDescription: match ? (match[5] ?? null) : (area.description ?? null),
    detailsKnown: Boolean(match),
  };
}

export function buildAffectedAreaPayload(area: NirAffectedAreaEntry) {
  const dimensions = `Dimensions: ${area.length}m × ${area.width}m × ${area.height}m. Materials: ${area.materials.join(", ")}`;
  return {
    ...(area.id ? { id: area.id } : {}),
    roomZoneId: area.roomZoneId,
    affectedAreaSqm: area.affectedSquareFootage,
    waterSource: area.waterSource,
    timeSinceLoss: area.timeSinceLoss,
    length: area.length,
    width: area.width,
    ...(area.detailsKnown !== false && { height: area.height }),
    materials: area.materials,
    // Untouched historical text stays in the existing server row. Re-sending
    // it can exceed the current 2,000-char schema or sanitize it differently.
    ...(area.detailsKnown === false ? {} : {
      description: area.originalDescription
        ? `${dimensions}\n\nOriginal note: ${area.originalDescription}`
        : dimensions,
    }),
  };
}
