-- Migration: ra_1461_client_summary_cache
-- RA-1461: Plain-English client-facing summary cache. Generated by Haiku 4.5
-- via lib/ai/client-summary.ts and exposed at POST /api/reports/[id]/client-summary.
-- Nullable so existing reports render without backfill; clientSummaryCachedAt
-- drives both the 5-minute rate limit and scope-change invalidation.

ALTER TABLE "Report"
  ADD COLUMN IF NOT EXISTS "clientSummaryCache" TEXT,
  ADD COLUMN IF NOT EXISTS "clientSummaryCachedAt" TIMESTAMP(3);
